### PR TITLE
ENH: Improve SH bases warning messages

### LINKED ISSUE #2449: Nonsense deprecation warning
I am getting this: 

```
 /opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/dipy/reconst/shm.py:339: PendingDeprecationWarning:
  
  The legacy descoteaux07 SH basis is outdated and will be deprecated in a future DIPY release. Consider using the new descoteaux07 basis.
```

Which makes no sense. See [here](https://github.com/yeatmanlab/pyAFQ/runs/3867843788?check_suite_focus=true#step:6:2895) for full context.

### PR DESCRIPTION
**Pull request by jhlegarreta**
- DOC: Fix typos in documentation
- ENH: Remove duplicate import statement
- ENH: Improve SH bases warning messages
- ENH: Rename test methods to avoid duplicate names
- ENH: Filter legacy SH bases warnings in tests

Closes #2449.

### CODE REVIEW

**Comment by jhlegarreta** [comment]
10a3700 closes #2449.

@arokem cross-referencing: https://github.com/dipy/dipy/pull/2348#issuecomment-961945972: dee04a1 fixes it. I preferred a simple renaming/I did not dig further to try to come up with names that suggest better what the tests do. Feel free to suggest/amend.

Note that we have over 5000+ warnings related to these:
```
denoise/tests/test_kernel.py: 4 warnings
direction/tests/test_bootstrap_direction_getter.py: 16 warnings
direction/tests/test_peaks.py: 25 warnings
direction/tests/test_pmf.py: 6 warnings
direction/tests/test_prob_direction_getter.py: 2 warnings
reconst/forecast.py: 99 warnings
reconst/shore.py: 44 warnings
reconst/tests/test_cross_validation.py: 26 warnings
reconst/tests/test_csdeconv.py: 59 warnings
reconst/tests/test_eudx_dg.py: 2 warnings
reconst/tests/test_forecast.py: 1646 warnings
reconst/tests/test_mapmri.py: 2349 warnings
reconst/tests/test_mcsd.py: 32 warnings
reconst/tests/test_qtdmri.py: 365 warnings
reconst/tests/test_shm.py: 65 warnings
reconst/tests/test_shore.py: 250 warnings
reconst/tests/test_shore_metrics.py: 380 warnings
reconst/tests/test_shore_odf.py: 223 warnings
tracking/tests/test_tracking.py: 5 warnings
workflows/tests/test_reconst_csa_csd.py: 129 warnings
workflows/tests/test_tracking.py: 16 warnings
```

e.g. visible in
https://dev.azure.com/dipy/dipy/_build/results?buildId=1351&view=logs&j=d9aefae6-c332-51b5-d933-a85009f5a2ac&t=7b3c05b2-26bc-5cc7-178d-37c39b6402cb&l=5188

This PR does not pretend to remove them all, unless we agree that it should. Besides providing a better testing of the warnings, it is primarily aimed at showing how these warnings should be filtered in order to avoid the clutter, including the changes in `direction/tests/test_prob_direction_getter.py` as a related/caller testing module example,

So the question is:
- Should all 5000+ warnings be removed in a single commit?
- Should all 5000+ warnings be removed in several commits in this PR?
- Should the remaining warnings be left for separate PRs in order to move forward?

I'm fine with whatever you decide @arokem @skoudoro .

A final note on how this cleans the output/avoids clutter that hinders spotting "real" issues/errors.

Before (locally):
```
....................................                                                                                                                                                                 [100%]
==== warnings summary ====
dipy/reconst/tests/test_shm.py: 65 warnings
  dipy/dipy/reconst/shm.py:338: PendingDeprecationWarning: The legacy descoteaux07 SH basis uses absolute values for negative harmonic degrees. It is outdated and will be deprecated in a future DIPY release. Consider using the new descoteaux07 basis by setting the `legacy` parameter to `False`.
    warn('The legacy descoteaux07 SH basis uses absolute values for '

dipy/reconst/tests/test_shm.py: 13 warnings
  dipy/dipy/reconst/shm.py:291: PendingDeprecationWarning: The legacy tournier07 basis is not normalized. It is outdated and will be deprecated in a future release of DIPY. Consider using the new tournier07 basis by setting the `legacy` parameter to `False`.
    warn('The legacy tournier07 basis is not normalized. It is outdated '

-- Docs: https://docs.pytest.org/en/stable/warnings.html
36 passed, 78 warnings in 0.78s
```

and
```
.                                                                                                                                                                                                    [100%]
==== warnings summary ====
dipy/direction/tests/test_prob_direction_getter.py::test_ProbabilisticDirectionGetter
dipy/direction/tests/test_prob_direction_getter.py::test_ProbabilisticDirectionGetter
  dipy/dipy/reconst/shm.py:338: PendingDeprecationWarning: The legacy descoteaux07 SH basis uses absolute values for negative harmonic degrees. It is outdated and will be deprecated in a future DIPY release. Consider using the new descoteaux07 basis by setting the `legacy` parameter to `False`.
    warn('The legacy descoteaux07 SH basis uses absolute values for '

dipy/direction/tests/test_prob_direction_getter.py::test_ProbabilisticDirectionGetter
dipy/direction/tests/test_prob_direction_getter.py::test_ProbabilisticDirectionGetter
  dipy/dipy/reconst/shm.py:291: PendingDeprecationWarning: The legacy tournier07 basis is not normalized. It is outdated and will be deprecated in a future release of DIPY. Consider using the new tournier07 basis by setting the `legacy` parameter to `False`.
    warn('The legacy tournier07 basis is not normalized. It is outdated '

-- Docs: https://docs.pytest.org/en/stable/warnings.html
1 passed, 4 warnings in 0.19s

``` 

After
```
...................................... [100%]
38 passed in 0.77s
```

and
```
. [100%]
1 passed in 0.21s

```

**Comment by jhlegarreta** [comment]
Linux Python37-64bit + OPTIONAL_DEPS: failing at `test_icm_square`
https://dev.azure.com/dipy/dipy/_build/results?buildId=1358&view=logs&j=d1321064-f6c3-56b7-0172-6d994d01c836&t=5b8ab677-55a5-5b41-0d20-670fdfa8c54f&l=4970

Linux Python38-64bit + MIN_DEPS: failing at `test_icm_square`
https://dev.azure.com/dipy/dipy/_build/results?buildId=1358&view=logs&j=e9afaa34-1a0f-534e-78fc-fae528ccd915&t=34ce0614-32e2-5b84-fa2a-64f8feae0bcb&l=6644
 
Windows CONDA Python37-64bit: failing at `test_nlmeans_4d_3dsigma_and_threads`
https://dev.azure.com/dipy/dipy/_build/results?buildId=1358&view=logs&j=4a0dadba-b014-54f8-0bf6-a2ee97567f21&t=f7cb4e1f-77dd-5be2-be6a-0e1fc5abfb48&l=3419

Windows Python37-64bit + OPTIONAL_DEPS: failing at `test_icm_square`
https://dev.azure.com/dipy/dipy/_build/results?buildId=1358&view=logs&j=a846d25a-e32c-5640-1b53-e815fab94407&t=2f8d848e-c100-586c-cef4-f5504e3b245e&l=3644

Windows Python38-64bit: failing at `test_nlmeans_4d_3dsigma_and_threads`
https://dev.azure.com/dipy/dipy/_build/results?buildId=1358&view=logs&j=0d467bef-f31d-5157-7a21-e4463e6da84d&t=143f92a6-744d-5785-9af0-d0b4ed86f2c2&l=3552

Unrelated to the patch set.

Having less warnings:
```
========= 879 passed, 27 skipped, 5810 warnings in 1209.77s (0:20:09) ==========
```
in https://dev.azure.com/dipy/dipy/_build/results?buildId=1351&view=logs&j=d9aefae6-c332-51b5-d933-a85009f5a2ac&t=7b3c05b2-26bc-5cc7-178d-37c39b6402cb&l=5188

```
========= 881 passed, 27 skipped, 5726 warnings in 1375.69s (0:22:55) ==========
```
in https://dev.azure.com/dipy/dipy/_build/results?buildId=1358&view=logs&j=d9aefae6-c332-51b5-d933-a85009f5a2ac&t=7b3c05b2-26bc-5cc7-178d-37c39b6402cb&l=5022

**Review by skoudoro — APPROVED** [review]
Thank you for tackling this @jhlegarreta and apologize for the delay.

> Should all 5000+ warnings be removed in a single commit?

no

> Should all 5000+ warnings be removed in several commits in this PR?

Not necessary

> Should the remaining warnings be left for separate PRs in order to move forward?

Yes, this can be done slowly


Overall, this PR looks good to me. 
It will be good if you could rebase.
All should come up green with fewer warnings and I will go ahead and merge this PR.

Thank you

**Comment by jhlegarreta** [comment]
> It will be good if you could rebase.

Done.

> no
> Not necessary

Will do then as time permits. At some point, after some sensible time, I guess the legacy bases should no longer be supported and these fixes will no longer be necessary. But for the time being, I do believe that this cleaning helps identifying better bugs, having a clean build, etc.

Side note: @skoudoro :100: for the effort of transitioning to GitHub Actions, and for improving the infrastructure. Having builds in the same place helps a lot.

**Comment by skoudoro** [comment]
All good, less warning, merging! Thank you @jhlegarreta

**Pull request merged**
