### PR TITLE
[WIP] Nlmeans update

### PR DESCRIPTION
**Pull request by itsayopapi**

### CODE REVIEW

**Comment by itsayopapi** [comment]
Fixed

**Comment by skoudoro** [comment]
Hi @itsayopapi,

Thank you for working on this. Can you compare the 2 versions of nlmeans and tell us what is the difference. You will have to check if both version gives the same results, the performance of both version and check the code of both version. 

thank you in advance for your feedback

**Comment by itsayopapi** [comment]
@skoudoro these are the following differences i took away from the 2 versions

Formatting and Readability: The revised version of the code has been formatted to ensure improved readability. The code is organized with proper indentation and line breaks, making it easier to follow.

Long Lines: Long lines in the original code that exceeded 80 characters have been split into multiple lines in the revised code to adhere to standard coding conventions.

Grammar and Typos: Grammar issues and a typo ("zeros like" instead of "zeros_like") in the original code have been corrected in the revised version.

Error Messages: The error messages in the original code have been improved for clarity.


Also in order to compare the two versions of the nlmeans code, we need to first test both versions with the same set of data and compare the results. This will ensure that both versions produce the same denoised output. also, measuring the execution time for each version will help us assess their performance efficiency. We need to  also inspect the code to identify any differences in logic or implementation. Performing unit tests and extensive testing on various input scenarios will help ensure the  reliability of both versions

**Comment by skoudoro** [comment]
> Also in order to compare the two versions of the nlmeans code, we need to first test both versions with the same set of data and compare the results. This will ensure that both versions produce the same denoised output. also, measuring the execution time for each version will help us assess their performance efficiency. We need to also inspect the code to identify any differences in logic or implementation. Performing unit tests and extensive testing on various input scenarios will help ensure the reliability of both versions

This look like a chatgpt answer 😅  and this is exactly what I am asking you to do. You can look at the tutorial to get the data.
Run the example, check performance, etc...

**Comment by itsayopapi** [comment]
@skoudoro i cant access the tutorial

**Comment by skoudoro** [comment]
What did you try ? @itsayopapi

**Comment by itsayopapi** [comment]
@skoudoro i tried this link https://dipy.org/

**Comment by skoudoro** [comment]
I am closing this PR for now. 

Please, feel free to reopen this PR when you have compare the 2 versions  (results, benchmark, etc...). Let us know if you have any specific/detailed question on #2950.

Thank you @itsayopapi

**Pull request closed without merging**
