### PR TITLE
NF - Added cython utility functions 

### PR DESCRIPTION
**Pull request by gabknight**
Utility functions for PTT tracking PR #2596.

Is there a good way to add unit tests on these?

### CODE REVIEW

**Comment by skoudoro** [comment]
Thanks @gabknight,

For the test, you can create a `test_fast_numpy.py` in `utils/tests` folder.

Inside the tests, check if np.dot is slower than your function and obtain the same result

**Comment by gabknight** [comment]
ok, thanks. I needed to change the function declaration from cdef to cpdef for the tests. Cross is 25x faster, dot is 1.5x on the length-3 vectors. There will more gain when doing the tracking in c.

**Review by skoudoro — APPROVED** [review]
Just waiting for the CI to finish and this PR is ready to be merged.

Thank you @gabknight

**Comment by skoudoro** [comment]
# SMALL NOTE

We need a system to allow pytest to run test on `cdef` files. In this file, `cpdef` are used just for the tests. This is not necessary. I suppose we need test as `pyx` files. Something to explore

**Pull request merged**
