### PR TITLE
Pushing 2nd blog,

### PR DESCRIPTION
**Pull request by shilpiprd**
This contains the 2nd blog.

### CODE REVIEW

**Comment by shilpiprd** [comment]
Ignore the changes made to conf.py file or sphixtext/docsracpe.py file , only changes i made was adding a blog.rst file

**Comment by skoudoro** [comment]
> Ignore the changes made to conf.py file or sphixtext/docsracpe.py file , only changes i made was adding a blog.rst file

This can not be ignored. Please, try to do a clean PR. You can rebase or just create a new PR starting from the most updated version of master branch.

**Comment by shilpiprd** [comment]
Alright, I created a new PR. #2823

**Comment by skoudoro** [comment]
superseded by #2823, closing

**Comment by shilpiprd** [comment]
okay

**Pull request closed without merging**
