### PR TITLE
Add tests to rng module

### LINKED ISSUE #1864: Add tests to dipy.core.rng
Unless I am missing something thing, classes implemented in this module don't seem to be used anywhere else.

### PR DESCRIPTION
**Pull request by skoudoro**
This PR adds tests for `WichmannHill2006`, `WichmannHill1982`, `LEcuyer`.

fix #1864

### CODE REVIEW

**Comment by arokem** [comment]
Any idea where that `global s1` variable is supposed to be defined?

**Comment by skoudoro** [comment]
It seems to be an old function, I think, I will make `s1` a parameter of this function. This is just a randomState. I do not know why it was global before but it does not seem adapted

**Comment by arokem** [comment]
👍 , which is why it's great that you are adding tests!

**Comment by skoudoro** [comment]
Thank you for the feedback 😃, update done and code rebased.

**Comment by arokem** [comment]
Why codecov thinks this is a *reduction* in coverage just baffles me. But off we go!

**Comment by skoudoro** [comment]
Agree, weird sometimes... I need to spend time to understand more Codecov one day...

**Pull request merged**
