### PR TITLE
add fig_kwargs

### PR DESCRIPTION
**Pull request by Borda**
I found quite convenient to add extra figure arguments

### CODE REVIEW

**Comment by skoudoro** [comment]
Thank you for this @Borda! 

Looks fine to me. Can you just fix the pep8 above and it is ready to be merged. 
Thank you

**Comment by Borda** [comment]
> Looks fine to me. Can you just fix the pep8 above and it is ready to be merged.

it looks like some unrelated issue...
`E   ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1076)`

**Comment by skoudoro** [comment]
Yes, I saw that, there is an issue for it (#2172)

**Comment by Borda** [comment]
> Yes, I saw that, there is an issue for it (#2172)

so I will wait till it is resolved... :]

**Comment by skoudoro** [comment]
Master has been fixed @Borda, you can rebase, and finalize your PR. Sorry for the delay

**Comment by Borda** [comment]
@skoudoro done :]

**Comment by skoudoro** [comment]
Thank you @Borda!

**Pull request merged**
