### PR TITLE
RF: Refactor `nn` module and deprecate `tensorflow` module

### PR DESCRIPTION
**Pull request by skoudoro**
This PR is a follow up of #3392. it manages Tensorflow and Pytorch backend from `nn`module. 

Pytorch becomes the preferred backend and Tensorflow a deprecated backend.

### CODE REVIEW

**Comment by pjsjongsung** [comment]
I'm guessing this let's us do `dipy.nn.evac.EVACPlus` instead of `dipy.nn.torch.evac.EVACPlus` now. I think you want to have a similar system in `histo_resdnn_torch_test.py` I believe?

Also I am not sure how modules work in python but I'm assuming, as the description says, it will be called before and after the tests in the file?

**Comment by skoudoro** [comment]
> I think you want to have a similar system in histo_resdnn_torch_test.py I believe?

it is the same system

> I'm assuming, as the description says, it will be called before and after the tests in the file?

not sure to understand your point here

**Comment by skoudoro** [comment]
> I'm guessing this let's us do dipy.nn.evac.EVACPlus instead of dipy.nn.torch.evac.EVACPlus

yes, both are possible, this is for backward compatibility

by default, this is "torch" backend but it can be modified by using an environment variable `DIPY_NN_BACKEND`

**Comment by pjsjongsung** [comment]
> > I think you want to have a similar system in histo_resdnn_torch_test.py I believe?
> 
> it is the same system
> 
> > I'm assuming, as the description says, it will be called before and after the tests in the file?
> 
> not sure to understand your point here

I meant like I do not see where the modules are called. Is it something that is automatically called by pytest?
Also I mentioned `histo_resdnn_torch_test.py` because I see it is not in the list of files changed.

**Comment by skoudoro** [comment]
Yes, `pytest` import automatically all modules and use the default backend which is pytorch. 
I need to reload the import when I want to use Tensorflow.  Otherwise, we will need to run twice `pytest`, one for each backend

**Comment by skoudoro** [comment]
is there any additional comments concerning this PR?

**Comment by Garyfallidis** [comment]
Pytorch wins.

**Comment by Garyfallidis** [comment]
We will need to run more benchmarks for the next stages. But good job for this release. Tensorflow to be deprecated ...

**Pull request merged**
