### PR TITLE
Support empty ArraySequence in transform_streamlines

### PR DESCRIPTION
**Pull request by frheault**
This emerged from testing conversion of empty tck/trk to vtk and its was crashing

### CODE REVIEW

**Comment by arokem** [comment]
Thanks for doing this! As always, a test that fails without this functionality would be a good addition to this PR.

**Comment by skoudoro** [comment]
2 CI matrices are failing because of `ray`. Are you aware of a change @arokem?  it failed by just importing the module....

**Comment by arokem** [comment]
Yeah. We need to pin the ray version for now, as in: https://github.com/dipy/dipy/pull/2593/commits/7628a780b5c077ae1a933a7cad45abce192d8ca7

**Comment by skoudoro** [comment]
> Yeah. We need to pin the ray version for now, as in: https://github.com/dipy/dipy/commit/7628a780b5c077ae1a933a7cad45abce192d8ca7

ok, good to know. Thanks!

**Review by skoudoro — COMMENTED** [review]
Hi @frheault,

it looks good to me. We might need to create a patch release of FURY before merging this PR since it fails [here](https://github.com/dipy/dipy/runs/6630377017?check_suite_focus=true#step:9:4087).

I also restarted some CI's matrix to make sure that everything is ok

**Pull request closed without merging**
