### PR TITLE
[UPCOMING] Release 1.8.0

### PR DESCRIPTION
**Pull request by skoudoro**
Preparation for 1.8.0 release, targeting **October 13, 2023**.

# Desired PR / issues (need review / feedback / update)

## PR

- [x]  #2759  (Submitter: @frheault)
- [x] #2906 (Submitter: @skoudoro)
- [x] ~~#2905 (Submitter: @maharshi-gor)~~
- [x] #2892 (Submitter: @gabknight)
- [x] ~~#2830 (Submitter: @shilpiprd)~~
- [x] #2825 (Submitter: @gabknight)
- [x] #2816 (Submitter: @shilpiprd)
- [x] #2781 (Submitter: @pjsjongsung)
- [x] #2715 (Submitter: @skoudoro)
- [ ] #1957 (Submitter: @skoudoro)
- [x] ~~#2036 (Submitter: @gabknight)~~
- [x] #2910 (Submitter: @DimitriPapadopoulos)
- [ ] #2932 (Submitter: @gabknight)

## Issues

- [x] #2736 
- [ ] ~~#2671~~ 
- [x] #2648
- [x] #2900
- [ ] #2886
- [x] #2878 
- [x] #2872
- [ ] #2866
- [x] #2815
- [x] #2801
- [x] #2794
- [x] #2777
- [x] #2703 

## Feature without PR yet:

- [x] Documentation update for website. (Update: #2923)
- [x] move benchmark files (Update: #2715)

Most of them can be done on time, I think :smile:

Please comment to flag any other issues or PR that should be addressed for this release

# Release checklist
- [x] add release_notes 1.8.0
- [x] Update changelog and api_changes
- [x] Update .mailmap
- [x] Set release number in info.py
- [x] Check the copyright years in doc/conf.py and LICENSE
- [x] Check documentation
- [x] Check Tutorial
- [x] Check unit test and USE-PRE
- [x] Update index.rst
- [x] Update Highligth.rst, old_news.rst, stateofheart.rst
- [x] Update developers.rst list
- [ ] Update website
- [x] Update deprecation cycle remove long deprecation

### CODE REVIEW

**Comment by DimitriPapadopoulos** [comment]
> [ ] add release_notes 1.6.0

Should be 1.8.0 :smile:

**Comment by skoudoro** [comment]
Good catch! updated

**Comment by skoudoro** [comment]
Hello all, 

The release will be delayed by 1 or 2 weeks.  we need #2759 and #2715 to get in. DIPY will not work on python 3.12 without #2715 which is out already. Those PR also need to be use a bit before the release. We do not want to rush this. So the new dates are:

- October 20, 2023 or October 27, 2023

Let us know if you have any requests or questions.

**Comment by arokem** [comment]
When you get a chance, could you rebase #2715? Definitely worth hammering that one out and figuring out any remaining issues after it's merged, before releasing.

**Comment by skoudoro** [comment]
> Looks like we should pin numpy<2.0 and/or make another small release in December

Yes I planned another release in December. we will be ok, I started to check, they are only few update to do.  My biggest worries is about our mandatory dependencies. we already have some issues with h5py and python3.12.
A subject to talk about in the next devs meeting.

**Comment by arnaudbore** [comment]
This also would be a nice and not much effort to add into 1.8.0 :tada: 
- [ ] https://github.com/dipy/dipy/pull/2956

**Comment by Garyfallidis** [comment]
Here we go! Fingers' crossed!

**Pull request merged**
