### PR TITLE
Adding diffusion data descriptions from references to reconstruction table

### PR DESCRIPTION
**Pull request by pcamach2**
Updates Reconstruction table to include descriptions of data acquired in references for more of the listed models. Links to DOIs for references are also added where `href`s  previously did not point to any URL.

### CODE REVIEW

**Comment by skoudoro** [comment]
Great! thank you! I might also commit 1-2 infos in your branch

**Comment by ShreyasFadnavis** [comment]
While we are on this, can someone change Anisotropic Power Map from Single & Multi-Shell -- to just Multi-Shell?

**Comment by skoudoro** [comment]
Paul just did @ShreyasFadnavis, Can you also provides ideal data requirement for IVIM and IVIM pro?  

Just write it in the comment, we will update it

**Comment by arokem** [comment]
> While we are on this, can someone change Anisotropic Power Map from Single & Multi-Shell -- to just Multi-Shell?

I don't think that this is correct. An APM can be calculated for any data for which CSD can be fit, including single shell data.

**Comment by ShreyasFadnavis** [comment]
> > While we are on this, can someone change Anisotropic Power Map from Single & Multi-Shell -- to just Multi-Shell?
> 
> 
> 
> I don't think that this is correct. An APM can be calculated for any data for which CSD can be fit, including single shell data.

Oh yeah! Sorry about that -- it needs a HARDI scheme I think, multi-shell is not a requirement. My bad🙈

**Comment by ShreyasFadnavis** [comment]
> Paul just did @ShreyasFadnavis, Can you also provides ideal data requirement for IVIM and IVIM pro?  
> 
> 
> 
> Just write it in the comment, we will update it

I think it's not simple to answer this question -- but it needs quite a bvals < 500. Maybe @arokem can answer this better than me?

**Comment by skoudoro** [comment]
Does someone want to add more information on this table? 

I think this PR is ready to go. We can still update it later. @ShreyasFadnavis ? @arokem ?

**Comment by ShreyasFadnavis** [comment]
I think we can merge this for now, will add more later for IVIM. We also need to work on making examples for the remaining reconstruction models, which maybe a good head-start for the new GSoC students- they'll get to know the API and have the chance to make an easy PR 😄

**Comment by skoudoro** [comment]
I will go ahead and merge this PR. This is a nice upgrade of this table. If we need to add more information, we can always create a new PR.

A nice update would be to improve the link to tutorials. 

Thank you very much for this @pcamach2! 

merging

**Pull request merged**
