### PR TITLE
ENH: Allow non-default parameters to `Patch2Self` CLI

### PR DESCRIPTION
**Pull request by jhlegarreta**
Allow specifying non-default parameters to `Patch2Self` CLI.

### CODE REVIEW

**Comment by jhlegarreta** [comment]
@ShreyasFadnavis @skoudoro See if this makes sense: I ignore whether these were left out purposely when adding the workflow; I assume it is safe to add them as they are/no special care needs to be taken depending on other parts of the workflow/parameter values. No new tests were added. The patch radius is not added as I think lists are not correctly dealt by the workflows yet.

**Comment by ShreyasFadnavis** [comment]
Hi @jhlegarreta ! Thanks a lot for this. I think the PR is good to go 😄 @skoudoro -- can you take a quick look and see if anything else is needed? If not, I can merge this on Monday morning.

**Review by skoudoro — COMMENTED** [review]
Can you update the tests @jhlegarreta? 

After that, it should be good to go.

**Comment by ShreyasFadnavis** [comment]
> Can you update the tests @jhlegarreta? 
> 
> 
> 
> After that, it should be good to go.

Not sure how we would test this apart from what we already have, since it's just exposing the options available...

**Comment by skoudoro** [comment]
@ShreyasFadnavis, after this change, CI's are failing, not sure why. 

Maybe one of the parameter (like `out_dtype=None`) can not be `None` because it is not handle by your algorithms. 

But I will let @jhlegarreta to look deeper at the default parameters and see why tests are failing

**Comment by jhlegarreta** [comment]
> Maybe one of the parameter (like out_dtype=None) can not be None because it is not handle by your algorithms.

The issue is not the `None` value in itself: other workflows do contain some `None` values by default for other parameters, e.g.
`SlrWithQbxFlow`, `SlrWithQbxFlow`, `ReconstDtiFlow`, `ReconstCSAFlow`, `ReconstIvimFlow`, or `MedianOtsuFlow`, and are tested in `DummyWorkflowOptionalStr` (if I read this correctly).

> But I will let @jhlegarreta to look deeper at the default parameters and see why tests are failing

The real issue lies in the assumption that all `out_` parameters correspond to filenames (except `out_dir` which is parsed to a dirname separately). Finding a fix requires some discussion and time: issue #2671.

In the meantime, I've removed the `out_dtype` parameter from the workflow.

**Review by skoudoro — APPROVED** [review]
LGTM, I will let @ShreyasFadnavis to have a last look and merge this PR. 

Thanks @jhlegarreta

**Comment by skoudoro** [comment]
And thanks for the issue too!

**Comment by ShreyasFadnavis** [comment]
Thanks @jhlegarreta ! Also thanks @skoudoro :) 

LGTM :) I will wait till tomorrow evening to merge this, in case anyone else has any other comments...

**Comment by ShreyasFadnavis** [comment]
Thanks @jhlegarreta @skoudoro and @araikes -- Merging!

**Pull request merged**
