### PR TITLE
[MNT] Drop distutils

### PR DESCRIPTION
**Pull request by skoudoro**
Drop `distutils` since it is deprecated

### CODE REVIEW

**Comment by arokem** [comment]
+1 thanks for doing this!

**Comment by skoudoro** [comment]
>  ModuleNotFoundError: No module named 'setuptools._distutils'

hard to find on Azure pipeline,  I will look into it, I can not generate this error locally. I suppose it depends on the `setuptools` version

**Comment by skoudoro** [comment]
Despite all these failing CI's, this PR is ready to go. All seems good now. I checked all failing CI's.  

In parallel, working on the failing CI's in https://github.com/skoudoro/dipy/pull/9

**Comment by arokem** [comment]
Just to verify that I understood your last message: the failing CIs are all unrelated to this PR?

**Comment by skoudoro** [comment]
> Just to verify that I understood your last message: the failing CIs are all unrelated to this PR?

Yes, sorry for the confusion

**Comment by arokem** [comment]
No worries! Merging

**Pull request merged**
