### PR TITLE
MAINT: Up Numpy version to 1.12.

### PR DESCRIPTION
**Pull request by arokem**
This should help with this: https://github.com/dipy/dipy/pull/2033#issuecomment-587558735. It seems that nibabel has upped their minimal requirement for 3.0
 and we can follow along.

### CODE REVIEW

**Comment by skoudoro** [comment]
Thank you @arokem! Let see what is the CI's result

**Comment by arokem** [comment]
It looks like the issue is with building h5py. I increased the minimal version of that as well.

**Comment by arokem** [comment]
Looks like this might resolve  the issue (works on travis, but has not been tested on azure yet). 

What are your thoughts? Any compelling reason to stay with h5py version 2.4? Version 2.5 was released in 2015.

**Comment by skoudoro** [comment]
Cool, Travis is passing! No reason to sta with h5py 2.4. We use the basic functionalities of h5py

**Comment by skoudoro** [comment]
I think this is ready to go. I just restarted an Azure pipeline Matrix to see everything green. When it is done I will merge it.

**Comment by skoudoro** [comment]
Thank you @arokem! merging

**Pull request merged**
