### PR TITLE
Fixes in regtools.py

### PR DESCRIPTION
**Pull request by kunakl07**

### CODE REVIEW

**Comment by ShreyasFadnavis** [comment]
Hi @kunakl07 Thank you for all your Pull Requests! I feel that 10+ Pull Requests for Grammatical Mistakes and Typos is a bit too much, and **gets hard to review**. Can you please close all of them and put them in one PR?

Thank you for the effort :+1: As soon as you put all of them in 1 PR, I think most of these changes are welcome!

**Comment by skoudoro** [comment]
> I feel that 10+ Pull Requests for Grammatical Mistakes and Typos is a bit too much, and gets hard to review. Can you please close all of them and put them in one PR?

Completely agree with this point. You can split them in 2-3 PRs, but 12 is quite a lot.  

Otherwise, Thank you @kunakl07 for this work

**Comment by kunakl07** [comment]
> Hi @kunakl07 Thank you for all your Pull Requests! I feel that 10+ Pull Requests for Grammatical Mistakes and Typos is a bit too much, and **gets hard to review**. Can you please close all of them and put them in one PR?
> 
> Thank you for the effort  As soon as you put all of them in 1 PR, I think most of these changes are welcome!

I apologize for the inconvenience. Yes, I will put them into 1 PR. Thanks a lot for the appreciation

**Comment by kunakl07** [comment]
> > I feel that 10+ Pull Requests for Grammatical Mistakes and Typos is a bit too much, and gets hard to review. Can you please close all of them and put them in one PR?
> 
> Completely agree with this point. You can split them in 2-3 PRs, but 12 is quite a lot.
> 
> Otherwise, Thank you @kunakl07 for this work

Yes, I will merge most of the PR's into one so that it is easy to review. Thanks for the appreciation

**Pull request closed without merging**
