### PR TITLE
Increased PTT performances

### PR DESCRIPTION
**Pull request by gabknight**
-  cythonized `find_closest(.)` from `dipy.core.shpere` to `dipy.direction.pmf`

-  optimized `pmf.get_pmf_value(.)`: only interpolated the direction of interest instead of the whole pmf.

-  improved cython code in `dipy.direction.ptt_direction_getter.pyx`

On my tests on the disco dataset, the performances improved by 5X.

### CODE REVIEW

**Comment by gabknight** [comment]
@skoudoro @Garyfallidis  I had to modify the `cpdef` to `cdef` in the `fast_numpy` functions to change the inputs from `double[:]` to `double*` . As such, I also had to remove the tests. Do we move forward like this? Another option would be to add `_c` to the `cdef` function names, and create `cpdef` functions with the same names that calls their respective `_c` functions. This option would be fine, but solely used for the testing. What do you think?

**Comment by skoudoro** [comment]
I am ok, with that only for fast_numpy module. 

In parallel, we need to figure out a way to add unit test for cdef functions

**Comment by skoudoro** [comment]
Can you comment then instead or deleting them for now ?

**Comment by gabknight** [comment]
This is ready for review. Further improvements will come in another PR.

**Review by skoudoro — APPROVED** [review]
Thank you @gabknight,

I am going ahead and merge this PR. Looks good to me.

**Pull request merged**
