### PR TITLE
DOC: fix typo in FW DTI tutorial

### PR DESCRIPTION
**Pull request by jchoude**
Really small typo

### CODE REVIEW

**Comment by arokem** [comment]
Do you want to make a PR against nipy/dipy? Or is this our new upstream?

**Comment by skoudoro** [comment]
Hi @arokem,

It will be our new upstream, we need to do an announcement at the same time as the release. 

Everything is already redirected normally. It missed, CI's and nipy.org/dipy to fix. If you catch something else, feel free to fix too 😄 !

Thank you @jchoude, for this fix!

**Comment by arokem** [comment]
@skoudoro : could you please give me permissions on this fork?

**Comment by skoudoro** [comment]
it is done, I sent a tonne of invitation. and you received one for the whole dipy organization

**Comment by skoudoro** [comment]
Did you find the invitation on your mail @arokem?

**Comment by arokem** [comment]
Yep. I'm in! Thank you.

**Comment by arokem** [comment]
Thanks @jchoude for this fix!

**Pull request merged**
