### PR TITLE
FIX: remove sagital from codespellrc ignore list

### LINKED ISSUE #3223: Remove`sagital`  from de codespell ignore list.
PR #3216 will not fix this issues. I added `sagital` to the whitelist; `codespell` is now passing. @skoudoro please open an issue to make it clear that the word should be removed once a new version of `codespell` is released.

_Originally posted by @jhlegarreta in https://github.com/dipy/dipy/issues/3218#issuecomment-2115189596_

### PR DESCRIPTION
**Pull request by skoudoro**
fix #3223.

Codespell has been release on May: https://github.com/codespell-project/codespell/releases/tag/v2.3.0.

it contains the new ignore keywords so we can remove `sagital` from the ignore list.

### CODE REVIEW

**Comment by skoudoro** [comment]
I believed that  codespellv2.3.0 will be picked up automatically. Do you know where I can force the version @jhlegarreta ?

**Comment by skoudoro** [comment]
I just asked here: https://github.com/codespell-project/actions-codespell/issues/70

**Comment by jhlegarreta** [comment]
Thanks for doing this Serge.

> I believed that codespellv2.3.0 will be picked up automatically. Do you know where I can force the version @jhlegarreta ?

Not sure, would have said that the action would take the latest version:
https://github.com/codespell-project/actions-codespell/blob/master/requirements.txt#L1

**Comment by skoudoro** [comment]
This PR start to bother me. 

is it ok if I remove codespell github action and replace it by adding codespell in pre-commit? At least, in pre-commit, I can control the version. Let me know what you think @jhlegarreta

**Comment by jhlegarreta** [comment]
> is it ok if I remove codespell github action and replace it by adding codespell in pre-commit? At least, in pre-commit, I can control the version. Let me know what you think @jhlegarreta

OK. Looks like it can be done: https://pre-commit.com/hooks.html, section `for text / docs / prose:`. So, after https://github.com/dipy/dipy/blob/544c284e12db041cb04a2004647fee8bf7cf68e5/.pre-commit-config.yaml#L12

BTW, I am not sure the spell checker is doing what we expect, since I have encountered other typos that I have fixed lately, e.g. c5e1dba and 0b8d8cb. Anyways, it will work as expected some day.

**Comment by skoudoro** [comment]
@jhlegarreta, it is ready to go!

**Review by jhlegarreta — APPROVED** [review]

**Pull request merged**
