### PR TITLE
TEST: Filter legacy SH bases warnings in tests

### PR DESCRIPTION
**Pull request by jhlegarreta**
Filter legacy SH bases warnings in tests. Warnings are already being
tested, and there is no further need to ensure that these warnings are
raised.

Filtering them avoids having them printed in the standard output, and
thus, unnecessary clutter.

Fixes:
```
workflows/tests/test_tracking.py: 16 warnings
dipy/venv/lib/python3.8/site-packages/dipy/reconst/shm.py:346:
PendingDeprecationWarning:
The legacy descoteaux07 SH basis uses absolute values for negative harmonic degrees.
It is outdated and will be deprecated in a future DIPY release.
Consider using the new descoteaux07 basis by setting the `legacy` parameter to `False`.
    warn(descoteaux07_legacy_msg, category=PendingDeprecationWarning)
```

and
```
direction/tests/test_peaks.py::test_peaks_shm_coeff
dipy/venv/lib/python3.8/site-packages/dipy/reconst/shm.py:302:
PendingDeprecationWarning:
The legacy tournier07 basis is not normalized.
It is outdated and will be deprecated in a future release of DIPY.
Consider using the new tournier07 basis by setting the `legacy` parameter to `False`.
    warn(tournier07_legacy_msg, category=PendingDeprecationWarning)
```

and similar warnings across modules.

Visible, for example, at:
https://github.com/dipy/dipy/runs/5235022769?check_suite_focus=true#step:9:3686

Follow-up of #2482.

### CODE REVIEW

**Comment by jhlegarreta** [comment]
So this cleans almost 6000 SH-basis related `PendingDeprecationWarning` warnings thrown in the tests:

```
========== 891 passed, 32 skipped, 197 warnings in 1336.62s (0:22:16) ==========
```
e.g. in https://github.com/dipy/dipy/runs/5260132767?check_suite_focus=true#step:9:3854

vs.
```
========= 891 passed, 32 skipped, 6090 warnings in 1310.68s (0:21:50) ==========
```

e.g. in https://github.com/dipy/dipy/runs/5256418766?check_suite_focus=true#step:9:3875


Only
```
reconst/forecast.py: 99 warnings
reconst/shore.py: 44 warnings
  /dipy/reconst/shm.py:346: PendingDeprecationWarning:
The legacy descoteaux07 SH basis uses absolute values for negative harmonic degrees.
It is outdated and will be deprecated in a future DIPY release.
Consider using the new descoteaux07 basis by setting the `legacy` parameter to `False`.
    warn(descoteaux07_legacy_msg, category=PendingDeprecationWarning)
```

(e.g. https://github.com/dipy/dipy/runs/5260132767?check_suite_focus=true#step:9:3750)

are left. They are left for a separate PR if needed. I have not investigated why the corresponding tests are not blamed.

**Comment by jhlegarreta** [comment]
The failing test is unrelated to this patch set:
https://github.com/dipy/dipy/runs/5260132768?check_suite_focus=true#step:9:3319

The commit in PR #2527 should fix it.

**Comment by jhlegarreta** [comment]
The failing test seems unrelated to this patch set:
```
        difference_map = np.abs(final_segmentation_1 - final_segmentation_2)
>       npt.assert_(np.abs(np.sum(difference_map)) != 0)
E       AssertionError

../venv/lib/python3.9/site-packages/dipy/segment/tests/test_mrf.py:370: AssertionError
```

https://github.com/dipy/dipy/runs/5277367984?check_suite_focus=true#step:9:3654

**Review by skoudoro — COMMENTED** [review]
Hi @jhlegarreta,

it seems there is still 1 or 2 left:

```python
reconst/forecast.py: 99 warnings
reconst/shore.py: 44 warnings
  /home/runner/work/dipy/dipy/venv/lib/python3.9/site-packages/dipy/reconst/shm.py:346: PendingDeprecationWarning: The legacy descoteaux07 SH basis uses absolute values for negative harmonic degrees. It is outdated and will be deprecated in a future DIPY release. Consider using the new descoteaux07 basis by setting the `legacy` parameter to `False`.
    warn(descoteaux07_legacy_msg, category=PendingDeprecationWarning)
```

Can you look at this?

Thanks

**Comment by jhlegarreta** [comment]
> it seems there is still 1 or 2 left:

Yes, that had been identified in https://github.com/dipy/dipy/pull/2526#issuecomment-1046089659

> Can you look at this?

See 72a94b4. These classes had some interactive session documentation that was presumably causing the warnings.

**Comment by skoudoro** [comment]
Great, Thank you for the update! merging

**Pull request merged**
