### PR TITLE
STYLE: Sort import statements using `ruff`

### PR DESCRIPTION
**Pull request by jhlegarreta**
Sort import statements using `ruff`.

Add a pre-commit hook to apply the import sorting to local files prior to commits.

Add a GHA workflow to apply the pre-commit hooks in order to ensure that files modified across commits/in PRs comply with the expected formatting.

### CODE REVIEW

**Comment by jhlegarreta** [comment]
This is another step towards making the code more consistent and hopefully more readable and expectable.

@skoudoro I know the mid-term plan is to switch to lazy loading (PR #3056). These rules will still be useful for when that happens. Mering this as soon as possible will help minimizing collisions, as this modifies virtually all files.

**Comment by jhlegarreta** [comment]
The actions is working as expected when it was applied to commit 70e3a34:
https://github.com/dipy/dipy/actions/runs/8676096801/job/23790235123?pr=3184#step:4:112

**Comment by jhlegarreta** [comment]
The `Stable / pip / build (3.11, ubuntu-latest, pip)` CI failure is unrelated:
https://github.com/dipy/dipy/actions/runs/8676186285/job/23790435428?pr=3184#step:10:4536

Not sure if it is failing on and off.

**Comment by jhlegarreta** [comment]
The reported test failure in `Optional Deps / pip / build (3.10, macos-latest, pip)` is unrelated (same as in https://github.com/dipy/dipy/pull/3183#issuecomment-2053712668):
https://github.com/dipy/dipy/actions/runs/8676186280/job/23790432708?pr=3184#step:10:480

**Comment by jhlegarreta** [comment]
`Visualization / VIZ / build (3.10, macos-latest, pip)` build failure is unrelated https://github.com/dipy/dipy/actions/runs/8676186280/job/23790432708?pr=3184#step:10:4809

**Review by skoudoro — APPROVED** [review]
Thank you  for this @jhlegarreta, 

All good, Merging

**Pull request merged**
