### PR TITLE
Removing tensorflow addon from DL models

### PR DESCRIPTION
**Pull request by pjsjongsung**
This commit is to remove the optional dependency of tensorflow addon due to its deprecation. I have also removed some repeated code in Synb0.

### CODE REVIEW

**Comment by skoudoro** [comment]
Thanks @pjsjongsung. 

is tensorflow addon replaced by something else?

**Comment by skoudoro** [comment]
Thank you for the clean up! 

Can you also remove it from the `pyproject.toml` and the `coverage.yml`  files? 

Then we can go ahead and merge this.

**Comment by pjsjongsung** [comment]
> Thanks @pjsjongsung.
> 
> is tensorflow addon replaced by something else?

It is going fully out of support and most of the functions are now replaceable with the functions in Tensorflow.



> Thank you for the clean up!
> 
> Can you also remove it from the `pyproject.toml` and the `coverage.yml` files?
> 
> Then we can go ahead and merge this.

Will do!

**Comment by skoudoro** [comment]
Thank you for the update @pjsjongsung, merging

**Pull request merged**
