### PR TITLE
DOC: Consider warnings as errors in documentation CI build

### PR DESCRIPTION
**Pull request by jhlegarreta**
Consider warnings as errors in documentation CI build.

### CODE REVIEW

**Comment by jhlegarreta** [comment]
2 of the `Build docs` warnings should be fixed by merging #3374 and #3375, and we will be left with issue #3347.

**Comment by jhlegarreta** [comment]
I'll rebase on `master` once #3379 gets merged. Builds should succeed without warnings after that.

**Comment by skoudoro** [comment]
> I'll rebase on master once https://github.com/dipy/dipy/pull/3379 gets merged. Builds should succeed without warnings after that.

done 👍 -> can be rebased

**Comment by jhlegarreta** [comment]
Documentation builds without warnings. Beautiful. Ready to be merged.

**Review by skoudoro — APPROVED** [review]
Great! Thank you for all this hard work @jhlegarreta! merging

Now, next step is #3270 with numpydoc (for later or a GSoC task). 

I experimented it with the following in the `conf.py`
```
error_ignores = {
    # These we do not live by:
    "GL01",  # Docstring should start in the line immediately after the quotes
    "EX01",  # No examples section found
    "EX02",  # examples failed (we test them separately)
    "ES01",  # no extended summary
    "SA01",  # no see also
    "YD01",  # no yields section
    "SA04",  # no description in See Also
    "PR04",  # Parameter "shape (n_channels" has no type
    "RT02",  # The first line of the Returns section should contain only the type, unless multiple values are being returned  # noqa
    # XXX should also verify that | is used rather than , to separate params
    # XXX should maybe also restore the parameter-desc-length < 800 char check
}

numpydoc_validate = True
numpydoc_validation_checks = {"all"} | set(error_ignores)
```

and I get this:

image

**Comment by jhlegarreta** [comment]
@skoudoro thanks for unlocking the last bit to make this possible.

As for

> and I get this:

:pensive:

I need a break from docstring tasks.

Having a build that reports these 3790 warnings would already be good so that we can see them openly and such that any members of the GRG or the community can fix them as time permits. GSoD might be good to address these as well.

A separate step or build would be required to report these warnings so that we do not take steps back in considering doc warnings as errors.

**Comment by jhlegarreta** [comment]
Additionally, it may be useful to have a preview of the documentation builds for each PR, as it would enable seeing how the docs are rendered and would enable spotting any formatting issue early with any new code documentation.

**Pull request merged**
