### PR TITLE
RF: Use new name for this function.

### PR DESCRIPTION
**Pull request by arokem**
This shouid eliminate warnings that now routinely appear

### CODE REVIEW

**Review by skoudoro — COMMENTED** [review]
Hi @arokem,

Thank you for this update!

it seems you are missing 2-3  `real_sph_harm` in `test_shm.py`. Also, you will have to update `test_default_lambda_csdmodel`.

Thanks !

**Comment by arokem** [comment]
Thanks for taking a look! I also took the opportunity to replace `real_sym_sh_basis` with `real_sh_descoteaux`.

**Review by skoudoro — COMMENTED** [review]
Hi @arokem,

You forgot to address the problem with `test_default_lambda_csdmodel`. You just need to update the number of warnings to be caught. 

After that, it should be ready to be in.

Thanks!

**Comment by arokem** [comment]
OK - I think I got it all now. Thanks for the quick review!

**Review by skoudoro — APPROVED** [review]
All Green, CI's Happy, I will merge this if there is no additional comment by the end of the day.

Thank you for this @arokem!

**Comment by jhlegarreta** [comment]
@arokem By changing the method name in here:
https://github.com/dipy/dipy/commit/343f81159f1a648178d1c58d8bf56241e440e350#diff-bcbfa34194cf36d07616911bb135804418eb5903801f5c0f2d65f24a88c6ada1R125

a duplication was introduced with an existing method name:
https://github.com/dipy/dipy/blob/master/dipy/reconst/tests/test_shm.py#L164

Thus, only the second one is being tested:
https://github.com/dipy/dipy/blob/master/dipy/reconst/tests/test_shm.py#L125
https://github.com/dipy/dipy/blob/master/dipy/reconst/tests/test_shm.py#L164

If the first one, which is calling the deprecated `real_sym_sh_mrtrix` method is renamed and kept, the deprecation message should be dealt with appropriately (cross-referencing PR #2478).

**Pull request merged**
