### PR TITLE
NF: Call `cnp.import_array()` explicitly to use the NumPy C API

### LINKED ISSUE #3265: NumPy 2.0 incompatibility
## Description
One of MNE-Python's CIs is failing due to a NumPy 2.0 incompatibility in DIPY. 

```
Traceback (most recent call last):
  File "/home/circleci/project/tutorials/inverse/50_beamformer_lcmv.py", line 316, in <module>
    morph = mne.compute_source_morph(
  File "<decorator-gen-489>", line 10, in compute_source_morph
  File "/home/circleci/project/mne/morph.py", line 262, in compute_source_morph
    shape, zooms, affine, pre_affine, sdr_morph = _compute_morph_sdr(
  File "/home/circleci/project/mne/morph.py", line 1147, in _compute_morph_sdr
    from dipy.align.imaffine import AffineMap
  File "/home/circleci/python_env/lib/python3.10/site-packages/dipy/align/__init__.py", line 26, in <module>
    from dipy.align._public import (syn_registration, register_dwi_to_template, # noqa
  File "/home/circleci/python_env/lib/python3.10/site-packages/dipy/align/_public.py", line 15, in <module>
    from dipy.align.metrics import CCMetric, EMMetric, SSDMetric
  File "/home/circleci/python_env/lib/python3.10/site-packages/dipy/align/metrics.py", line 7, in <module>
    from dipy.align import vector_fields as vfu
  File "vector_fields.pyx", line 1, in init dipy.align.vector_fields
ImportError: numpy.core.multiarray failed to import (auto-generated because you didn't call 'numpy.import_array()' after cimporting numpy; use '<void>numpy._import_array' to disable if you are certain you don't need it).
```

That CI is running Ubuntu 22.04, Python 3.10, and

```
Package                       Version                Editable project location
----------------------------- ---------------------- -------------------------
cvxpy                         not installed
dipy                          1.9.0
fury                          not installed
h5py                          3.11.0
mne                           1.8.0.dev72+gc24702cb9 /home/circleci/project
nibabel                       5.2.1
numpy                         2.0.0
scipy                         1.13.1
```

To reproduce, create environment w/ the above deps, and run the tutorial file: https://mne.tools/dev/auto_tutorials/inverse/50_beamformer_lcmv.html

## Way to reproduce
- [x] Code example
- [x] Relevant images (if any)
- [x] Operating system and version (run `python -c "import platform; print(platform.platform())"`)
- [x] Python version (run `python -c "import sys; print('Python', sys.version)"`)
- [x] dipy version (run `python -c "import dipy; print(dipy.__version__)"`)
- [x] dependency version (numpy, scipy, nibabel, h5py, cvxpy, fury)
    * import numpy; print("NumPy", numpy.__version__)
    * import scipy; print("SciPy", scipy.__version__)
    * import nibabel; print("Nibabel", nibabel.__version__)
    * import h5py; print("H5py", h5py.__version__)
    * import cvxpy; print("Cvxpy", cvxpy.__version__)
    * import fury; print("fury", fury.__version__)

### PR DESCRIPTION
**Pull request by jhlegarreta**
Call `cnp.import_array()` explicitly to use the NumPy C API: Cython modules (or anything using the NumPy C API) must call `cnp.import_array()` to import the NumPy C API.

Fixes:
```
  File "vector_fields.pyx", line 1, in init dipy.align.vector_fields
ImportError: numpy.core.multiarray failed to import
 (auto-generated because you didn't call 'numpy.import_array()' after
 cimporting numpy; use '<void>numpy._import_array' to disable if you
 are certain you don't need it).
```

reported by third-party tool (e.g. MNE) maintaners when testing their tools with NumPy 2.0.

Fixes #3265.

### CODE REVIEW

**Comment by jhlegarreta** [comment]
We need to add NumPy 2.0 to the stack of tested dependencies.

**Comment by jhlegarreta** [comment]
OK, all are failing. Should be compatible with NumPy<2.0.0, e.g. has been there since a few years now:
https://github.com/numpy/numpy/commit/e9e0a8c32e72d739e4bb637bc85bb2b5a42545c7

I've seen this:
https://github.com/pandas-dev/pandas/blob/main/pyproject.toml#L9-L11
https://github.com/pandas-dev/pandas/blob/main/pyproject.toml#L30-L31

Also in `scikit-imae`:
https://github.com/scikit-image/scikit-image/blob/main/pyproject.toml#L56
https://github.com/scikit-image/scikit-image/blob/main/pyproject.toml#L29

Additionally, here they mention that `PyArray_ImportNumPyAPI` is preferred over `import_array`:
https://numpy.org/doc/stable/release/2.0.0-notes.html#new-c-api-import-functions

So not sure about the way forward.

**Comment by jhlegarreta** [comment]
Well, does not look like the build-system change worked in cd38e8d.

**Comment by jhlegarreta** [comment]
So remaining errors:
 - Not sure the approach to solve this: `ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject`, but Python 3.12 builds are not reporting those errors, probably thanks to 7b61aff6663b51c518245a5e3d3217b1583ab16a and possibly a5e6f26784460170b1814f10d732212d456fec48.
 Other errors to be addressed: https://github.com/dipy/dipy/actions/runs/9605741685/job/26493943578?pr=3266#step:10:10353
- `CVXPY` reporting issues:
https://github.com/dipy/dipy/actions/runs/9605741677/job/26493933074?pr=3266#step:10:135
   We may need to bump the min version in e.g. https://github.com/dipy/dipy/blob/d5e34fbdca1a30829060827f944b5aeb9f145e75/dipy/core/optimize.py#L13
  according to https://github.com/cvxpy/cvxpy/issues/2474#issuecomment-2175018262

**Comment by skoudoro** [comment]
Hi @jhlegarreta, 

Thank you for this PR. Can you rebase it?

**Comment by jhlegarreta** [comment]
> Can you rebase it?

Done.

**Comment by jhlegarreta** [comment]
Run out of ideas to fix the data type size issues :confused:.

**Comment by skoudoro** [comment]
Hi @jhlegarreta,

I am not sure to understand your approach and what you are trying to achieve in this PR. 

Maybe #3274 could help.

I do not think we need `cnp.import_array()`. Let me know what you think and thank you for your feedback

**Comment by jhlegarreta** [comment]
> I am not sure to understand your approach and what you are trying to achieve in this PR.

c74f656 tried to address the issues as explained in https://github.com/dipy/dipy/pull/3266#issue-2360882282. Those issues are also being reported by the CIs, e.g.
https://github.com/dipy/dipy/actions/runs/9691442240/job/26742933573#step:10:11351
```
E   ImportError: 
numpy.core.multiarray failed to import (auto-generated because you didn't call 'numpy.import_array()' 
after cimporting numpy; use '<void>numpy._import_array' to disable if you are certain you don't need it).
```

> Maybe https://github.com/dipy/dipy/pull/3274 could help.

If I read well, that PR takes (a slight variation of) c5b3f32 and e692764 that exist in this PR.

> I do not think we need cnp.import_array(). Let me know what you think and thank you for your feedback

As per your PR, it looks like the `cnp.import_array()` calls that try to address the mentioned error may be a by-product of the NumPy version used to compile the code, and thus they shall not be required.

**Comment by skoudoro** [comment]
ok I see now.

The errors in https://github.com/dipy/dipy/pull/3266#issue-2360882282 are due to the DIPY build with the wrong version of Numpy which make sense. Fixing the build fix those errors.

> (a slight variation of) https://github.com/dipy/dipy/commit/c5b3f32f16ae1c5c38c42764cb29a0406fec3ff5 and https://github.com/dipy/dipy/commit/e692764bef8c03b354b7b47fb213e1a3b06372a4 that exist in this PR.

the idea was good but both commit are wrong because they do not address correctly the issue. Here, only the `build` section is important. we need to make sure to always build with Numpy>=2.0.0 and the last cython version allow that.

However dependencies can be lower since the build support the use of lower version of numpy.

So I will close this PR. Thank you so much for working on this and your help in general @jhlegarreta.

**Pull request closed without merging**
