### PR TITLE
MAINT: Update import from ndimage

### PR DESCRIPTION
**Pull request by larsoner**
Avoids deprecation warnings in SciPy `master` about importing from `scipy.ndimage.measurements` EDIT: *and other similar namespaces*

### CODE REVIEW

**Comment by arokem** [comment]
LGTM! Thanks for doing that. I think that as soon as the CI comes back green, we can go ahead and merge this.

**Comment by larsoner** [comment]
One CI failure should be fixed by https://github.com/dipy/dipy/pull/2436, the other is noted there but I'm not sure what the fix is. It seems unrelated to these changes, though.

**Review by skoudoro — COMMENTED** [review]
+1 for merging this. 

#2436 has been merged, so can you rebase or merged master into your branch.

CI should be green now. 

Thank you for this update @larsoner!

**Comment by skoudoro** [comment]
I going ahead and merge this PR. The failing CI's are not due to this PR.

Thanks @larsoner!

**Pull request merged**
