### PR TITLE
Feature/surface

### PR DESCRIPTION
**Pull request by maharshi-gor**
This PR allows horizon to read .pial files and display the surfaces.

### CODE REVIEW

**Comment by skoudoro** [comment]
Also, it would be great if you could handle the extension `.white`  and `.inflated`

**Comment by maharshi-gor** [comment]
> Hi @maharshi-gor, Where can I find pial files to test this PR? does it accept other types or files like vtk files ?

Hi @skoudoro 
you can use lh.pial files and we just support this format for time being
https://fcp-indi.s3.amazonaws.com/index.html#data/Projects/HBN/derivatives/Freesurfer_version6.0.0/NDARAA536PTU/surf/

**Comment by skoudoro** [comment]
Ok, I download, the first one `lh area pial surface.pial`. and unfortunately, it fails.  This PR needs to improve error management.

See below the error:
```python
❯ dipy_horizon --force /Users/skoudoro/Downloads/lh\ area\ pial\ surface.pial
INFO:The following output files are about to be overwritten.
INFO:tmp.png
Loading file ...
/Users/skoudoro/Downloads/lh area pial surface.pial


Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniforge/base/envs/py39/bin/dipy_horizon", line 8, in <module>
    sys.exit(run())
  File "/Users/skoudoro/devel/dipy/dipy/workflows/cli.py", line 59, in run
    run_flow(getattr(mod, flow_name)())
  File "/Users/skoudoro/devel/dipy/dipy/workflows/flow_runner.py", line 88, in run_flow
    return flow.run(**args)
  File "/Users/skoudoro/devel/dipy/dipy/workflows/viz.py", line 183, in run
    vertices, faces = load_pial(fname)
  File "/Users/skoudoro/devel/dipy/dipy/io/surface.py", line 20, in load_pial
    return nib.freesurfer.read_geometry(fname, read_metadata=return_meta)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/py39/lib/python3.9/site-packages/nibabel/freesurfer/io.py", line 151, in read_geometry
    quads = _fread3_many(fobj, nquad * 4)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/py39/lib/python3.9/site-packages/nibabel/freesurfer/io.py", line 51, in _fread3_many
    b1, b2, b3 = np.fromfile(fobj, '>u1', 3 * n).reshape(-1, 3).astype(int).T
ValueError: cannot reshape array of size 611794 into shape (3)
```

**Review by skoudoro — CHANGES_REQUESTED** [review]
Hi @maharshi-gor,

See my comments above. Also, it needs some tests. Thanks

**Comment by maharshi-gor** [comment]
> ```python
> .
> ```

Hi @skoudoro 
I looked into nibabel's freesurfer module which we are using here to open pial files.

https://nipy.org/nibabel/reference/nibabel.freesurfer.html

The .pial files can have different things than surfaces. we do not have a way to detect if the file has geometry data or not.
I am not sure how should I capture the exception.

Should I just catch the exception and provide a message saying this is not a correct .pial file.

can you help me with some solution here

Thanks

**Comment by skoudoro** [comment]
Hi @maharshi-gor ,

Keep it simple for now, add `try/except` and if it fails, raise a more friendly message.  if it succeed, check if it is vertices + faces via their shape. if not, same raise a friendly message

**Comment by maharshi-gor** [comment]
> Hi @maharshi-gor ,
> 
> Keep it simple for now, add `try/except` and if it fails, raise a more friendly message. if it succeed, check if it is vertices + faces via their shape. if not, same raise a friendly message

Got it, Thanks!

**Pull request merged**
