### PR TITLE
RF - Removed deprecated tracking code

### PR DESCRIPTION
**Pull request by gabknight**
While working on PR #2368, I noticed this deprecated code (since 1.2.0).

Should this be removed for 2.0?

### CODE REVIEW

**Review by skoudoro — COMMENTED** [review]
Hi @gabknight,

After 2 releases and the third one coming soon,  +1 for deleting this deprecated code.

Can you add a note to `api_change.rst`?

Thank you

**Comment by gabknight** [comment]
Ok! Thanks @skoudoro

**Review by skoudoro — COMMENTED** [review]
Hi @gabknight,

Tests are failing because you need to remove [this import](https://github.com/dipy/dipy/pull/2384/files#diff-d97ecd0cd039abb60b07e195991e30d980afd49048e511035cd7d7fc7f80940eR7) from `dipy/reconst/tests/test_eudx_dg.py`

**Comment by gabknight** [comment]
oops, thanks @skoudoro

**Comment by skoudoro** [comment]
thank you @gabknight. merging

**Pull request merged**
