### PR TITLE
Enhancing Gradient Approximation in DTI Tests #3155

### PR DESCRIPTION
**Pull request by tanishka321**
I've introduced a D_perturbed variable that is slightly different from the ground truth D_orig. By perturbing D away from the minimum, we avoid approximating the derivative at the minimum, as suggested. 

#3155

### CODE REVIEW

**Comment by tanishka321** [comment]
Here is an outline I had been thinking of (soon will be addressing other issues), are these considerable?

**Comment by skoudoro** [comment]
Thank you for doing this @tanishka321. Maybe @samcoveney can have a look since this is the initiator of the issue.

**Comment by samcoveney** [comment]
Hi @tanishka321 thanks for the work. I think you may have misunderstood #3155 though - the original test with _non-perturbed_ D works with autograd already, meaning my suggestion in #3155 could be implemented mostly as is.

But note that this would (1) require to add `autograd` as a dependancy, which is why your tests have error `ERROR reconst/tests/test_dti.py - ModuleNotFoundError: No module named 'autograd'` and (2) would require using `autograd` in `dti.py` (as far as I am aware, or it is not possible to use `grad` on `nlls.err_func` - did your tests pass locally?)

I don't think this is the way to go if we can avoid it. Instead, I would suggest to check if you can get the original gradient estimation with `opt.approx_fprime` working with `D_perturbed`. If that works and passes tests, problem solved.

**Comment by samcoveney** [comment]
any progress on this @tanishka321 ?

**Comment by skoudoro** [comment]
I am closing this PR for now, but feel free to reopen it when you feel ready! 

Thank you for this work @tanishka321 and thank you for the review @samcoveney

**Pull request closed without merging**
