### PR TITLE
[FIX] Cleanup deprecated np.float, np.bool, np.int

### PR DESCRIPTION
**Pull request by skoudoro**
This PR fixes the following warnings:
```python
DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
  Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
  Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
  Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

```

### CODE REVIEW

**Comment by skoudoro** [comment]
This PR is ready to be merged. 

Can someone have a look? 

Thank you

**Comment by arokem** [comment]
Thanks for doing this. 

Are you sure you don't want to specify the precision? `np.float32` `np.float64` instead of the builtin `float`?

I assume this will do different things on different platforms...?

**Comment by skoudoro** [comment]
> I assume this will do different things on different platforms...?

yep, `float` is platform-dependent. Most of the changes do not need to force to float64. No need to increase memory. There are few cases questionable but it can be changed afterward if we see that it limits us too much.

thank you for the review and the question @arokem

**Comment by arokem** [comment]
Cool. That makes sense. Merging!

**Pull request merged**
