### PR TITLE
ENH: Fix miscellaneous warnings

### PR DESCRIPTION
**Pull request by jhlegarreta**
- ENH: Prefer using an Input(shape) as first layer in Sequential models
- TEST: Filter legacy SH bases warnings in histology ResDNN model test

### CODE REVIEW

**Comment by skoudoro** [comment]
Thank you @jhlegarreta 

> ENH: Prefer using an Input(shape) as first layer in Sequential models

this is fixed in https://github.com/dipy/dipy/pull/3139 and I was going to merge it first

**Comment by skoudoro** [comment]
Can you rebase or merge master?  Thanks!

**Comment by jhlegarreta** [comment]
> Can you rebase or merge master? Thanks!

Done.

**Comment by jhlegarreta** [comment]
Warnings are gone:
https://github.com/dipy/dipy/actions/runs/8375586646/job/22933247338?pr=3141#step:10:6798

Coverage, Stable Python 3.12 build errors are unrelated:
https://github.com/dipy/dipy/actions/runs/8375586646/job/22933247338?pr=3141#step:11:80
https://github.com/dipy/dipy/actions/runs/8375586645/job/22933251811?pr=3141#step:10:3921

**Review by skoudoro — APPROVED** [review]
LGTM, Thank you @jhlegarreta, merging

**Pull request merged**
