### PR TITLE
Robust split idea rebase arokem

### PR DESCRIPTION
**Pull request by arokem**
This adds d1379f33882fe15f3cf82fcd9f5c0226f29db802 on top of #3358

### CODE REVIEW

**Comment by skoudoro** [comment]
Thank you for this !

build docs and code format are still failing. make sure to use 
``` 
pip install pre-commit
pre-commit install
pre-commit run --files  my_files.py
```
concerning code format.

**Comment by skoudoro** [comment]
Thank you for cleaning up. I will look why `build docs` CI is failing here and not in the other PRs. Then we can merge

**Comment by skoudoro** [comment]
Ok, I fixed the doc issues. I have made a PR on your branch: https://github.com/arokem/dipy/pull/39

**Comment by arokem** [comment]
Thanks!

**Comment by samcoveney** [comment]
@skoudoro you say in #3358 that the parallel back-end doesn't work, but it does seem to be working for me, can you clarify what you mean please?

Also, if working off this branch, please make sure my name appears very clearly in the merge log - I need to be able to show people that this is my PR, otherwise they won't know what I've been doing

**Comment by skoudoro** [comment]
> but it does seem to be working for me, can you clarify what you mean please?

To clarify, in DKI, we do not pass `**kwargs` to all the `fit` functions.  So, we can not pass a backend to multivoxelfit when we call the fitting (e.g `dkifit.fit(data, engine='ray')`). I believed that it has been updated by @arokem, but I might be wrong.

That's fine, it can be fixed and tested later.  Now we always use the `serial` backend by default with multivoxelfit.

for DTI, it is normal, we never use the multivoxelfit decorator. The current method is fast enough.

> please make sure my name appears very clearly in the merge log

Since I am not 100% sure, 2 options:
- either you cherry pick the 3 last commits from this PR on your PR @samcoveney 
- either, @arokem needs to update the commit message and make sure that it is not "co-authored" (in the commit message text) like it is above. a `git rebase interactive` should be enough. a small link explaining the procedure: https://github.com/orgs/community/discussions/76660#discussioncomment-7649637

Not sure what will be the fastest to do that and make sure all is ok. Please, both, let me know.

**Comment by samcoveney** [comment]
I have no problem with having co-authors (thanks for the help!) but please put me first; also the name of this branch kind of makes it look like @arokem wrote it - I kind of would prefer that the branch name didn't suggest that someone else did 99% of the work ;)

**Comment by samcoveney** [comment]
The authorship is important to the reports we need to submit regarding what the grant money actually did! Obviously, there are papers as well, but this is also quite important I think

**Comment by samcoveney** [comment]
Like I say, I'm happy to have the co-authorship on the commit, if you're able to just modify the branch name to something like "Robust split idea rebase tidy", I am happy to proceed as is. Just make sure I'm clearly named as an author, and that should be enough.

**Comment by arokem** [comment]
Closed in favor of #3403

**Pull request closed without merging**
