### PR TITLE
[WIP] Sphinx-Gallery integration

### PR DESCRIPTION
**Pull request by skoudoro**
The goal is to replace our example doc generation system by Sphinx-gallery.

TODO
====
- [ ] Update all examples syntax
- [ ] Change workflow tutorials, sphinx-gallery fails when I add them
- [ ] check design with our new website
- [ ] update doc/readme instruction
- [ ] update make for Linux and window
- [ ] Remove our system? Should we keep it or I can go ahead and delete it? 
- [ ] Check links and references

Below, the result of a quick test : 

image

image

### CODE REVIEW

**Comment by skoudoro** [comment]
To test this branch on Windows:  `./make.bat html-after-examples`. it will skip our system and use sphinx-gallery only to generate all tutorials.

**Comment by skoudoro** [comment]
**Personal Note**: Need to check the coherence between the subsection system with `sphinx-gallery` and the current URL path of our system to avoid more redirection...

**Comment by arokem** [comment]
This looks great! I have not run it all the way through yet, but it looks good on paper. 

> Remove our system? Should we keep it or I can go ahead and delete it?

I think that we should remove our system. No need to keep it once this is up and running.

**Comment by skoudoro** [comment]
BTW, This will break all our current SEO, I'm trying to figure out how can we keep this...

**Comment by arokem** [comment]
@skoudoro : since it just came up again in #2094, where does this one stand? Did you figure out the SEO issue? Can we just go ahead with this, and hope that Google updates the links in a timely fashion? I believe it usually takes just a few weeks.

**Comment by skoudoro** [comment]
> where does this one stand? Did you figure out the SEO issue?

No, I did not find a nice workaround @arokem 

> Can we just go ahead with this, and hope that Google updates the links in a timely fashion? I believe it usually takes just a few weeks.

ok, I am fine with that, I will come back to this PR asap

**Comment by ShrishtiHore** [comment]
Sure @skoudoro I will be waiting for your response. Would love to contribute to this.

**Comment by arokem** [comment]
Did we give up on this one?

**Comment by skoudoro** [comment]
wrong GitHub command... I went a bit fast... it seems that I deleted my work.... 😭.  If you know how to get it back @arokem, just hangout me, otherwise, I will restart from scratch...

**Comment by skoudoro** [comment]
Oh, I think I see how to get it back, let me try...

**Pull request closed without merging**
