### PR TITLE
Adds  for the dipy.align._public module

### PR DESCRIPTION
**Pull request by arokem**

### CODE REVIEW

**Comment by arokem** [comment]
Potentially closes #2290

**Comment by larsoner** [comment]
Note that if you build docs locally or have some artifact on Azure or CircleCI with `objects.inv` you can run the same `grep` check as in #2290 to find out if it's fixed, like
```
$ python -m sphinx.ext.intersphinx _build/html/objects.inv | grep " *dipy\.align.*AffineMap .*"
	dipy.align.imaffine.AffineMap            reference/dipy.align/#dipy.align.imaffine.AffineMap
```

**Comment by skoudoro** [comment]
I checked with your PR @arokem and this is what I obtain:

```
python -m sphinx.ext.intersphinx _build/html/objects.inv | grep " *dipy\.align.*AffineMap .*"
        dipy.align._public.AffineMap             reference/dipy.align.html#dipy.align._public.AffineMap
        dipy.align.imaffine.AffineMap            reference/dipy.align.html#dipy.align.imaffine.AffineMap
``` 

So it does not fix it.

BTW, when I run the same command for the release 1.3.0, I obtain:

```
(dipy-env-37) MacBook-Pro-de-koudoro:doc koudoro$ python -m sphinx.ext.intersphinx https://dipy.org/documentation/1.3.0./objects.inv | grep " *dipy\.align.*AffineMap .*"
        dipy.align._public.AffineMap             reference/dipy.align/#dipy.align._public.AffineMap
        dipy.align.imaffine.AffineMap            reference/dipy.align/#dipy.align.imaffine.AffineMap
(dipy-env-37) MacBook-Pro-de-koudoro:doc koudoro$ 
```

Both paths seem to appears so I still do not understand why the link is broken in your doc @larsoner.

**Comment by larsoner** [comment]
I must have copy-pasted my commands improperly before somehow. Testing it now, I see what you see @skoudoro. Looking back at one CircleCI build we had a connection problem at least once:
```
WARNING: failed to reach any of the inventories with the following issues:
intersphinx inventory 'https://dipy.org/documentation/1.1.1./objects.inv/' not fetchable due to <class 'requests.exceptions.ConnectionError'>: HTTPSConnectionPool(host='dipy.org', port=443): Max retries exceeded with url: /documentation/1.1.1./objects.inv/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb875b54e20>: Failed to establish a new connection: [Errno 111] Connection refused'))
```
And that led to some linking errors.

So I think the only *real* problem is that the name in the HTML is `_public.*`.

**Comment by larsoner** [comment]
(Sorry for the other noise!)

**Comment by skoudoro** [comment]
We have both names in the HTML too: 

- https://dipy.org/documentation/1.3.0./reference/dipy.align/#dipy.align.imaffine.AffineMap
- https://dipy.org/documentation/1.3.0./reference/dipy.align/#dipy.align._public.AffineMap

But I agree, it is not clean. we should fine a solution to have only `dipy.align.imaffine.AffineMap`.

**Comment by skoudoro** [comment]
This PR looks good but does not fix the original problem. I will go ahead and merge it if there is no additional comment by tomorrow evening. 

We need to look at [this script](https://github.com/dipy/dipy/blob/master/doc/tools/apigen.py) to fix our issue with API doc and interpshinx.

**Comment by skoudoro** [comment]
thanks @arokem

**Pull request merged**
