### PR TITLE
BF: refer to cigar_tensor

### PR DESCRIPTION
**Pull request by fnery**
Found a small bug in the new code for multidimensional gradient table support.

### CODE REVIEW

**Comment by arokem** [comment]
Yikes. Good catch! Let's wait for the CI to finish and then merge.

**Comment by arokem** [comment]
Hey @skoudoro : do you understand these Azure failures? It looks like it's timing out before it even gets started. But to be honest: I couldn't quite understand where I was supposed to look for the error. The interface is not the most intuitive...

**Comment by skoudoro** [comment]
> Hey @skoudoro : do you understand these Azure failures? It looks like it's timing out before it even gets started. But to be honest: I couldn't quite understand where I was supposed to look for the error. The interface is not the most intuitive...

I did not find yet the reason for this timeout. Still trying to find out the reason and it will take time. I am ok if you want to merge this PR since the failure is not related.

**Comment by ShubhamShaswat** [comment]
Hi,So I did some check on errors found out that somehow the error may be coming from the below mentioned packages.
`../venv/lib/python3.7/site-packages/fury/primitive.py:8:`
The error which kept poping up is due to this line 8:
`from scipy.spatial import transform`

Error : 
```
ImportError: cannot import name 'transform' from 'scipy.spatial' 

Hint: make sure your test modules/packages have valid Python names.
```
May be this will help you

**Comment by skoudoro** [comment]
Thank you for looking @ShubhamShaswat, but this is not the error we are tracking.
This one is an easy fix. You can [here](https://dev.azure.com/dipy/dipy/_build/results?buildId=218&view=logs&jobId=15f8dc28-9f6f-5e3a-5b3c-2b169071e5be&j=15f8dc28-9f6f-5e3a-5b3c-2b169071e5be&t=afdcd536-9a2c-56b1-93fe-7fd9c8c7aeff) to see the error we are talking about.

**Comment by ShubhamShaswat** [comment]
Thanks @skoudoro ,I will try to look into it

**Comment by arokem** [comment]
Thanks!

**Pull request merged**
