### PR TITLE
[DOC]: Change defaults in Patch2Self example

### PR DESCRIPTION
**Pull request by ShreyasFadnavis**
Hi everyone,

I know that the defaults in `Patch2Self` were changed recently by @arokem, but they won't be visible to the users until the next release. I am making this small PR for adding it to the documentation to ensure that people still use the correct options!

@skoudoro : would it be possible to update the documentation with these changes before the next release?

### CODE REVIEW

**Review by skoudoro — APPROVED** [review]
Thank you @ShreyasFadnavis.

If no other comment by the end of the day, I will go ahead and merge this PR.

**Comment by arokem** [comment]
This additional documentation is valuable! But most users will not see this either, until it makes it into a release. 

Should we cut a quick 1.4.1 to propagate these changes out? @skoudoro : would that be terribly onerous?

**Comment by skoudoro** [comment]
> would that be terribly onerous?

Since we did not do any announcement concerning the release of 1.4.0 because of the workshop, we can do that. It will be easier. 

Let's cut this release 1-2 weeks from now, it will let us time to finalize some small issues

**Comment by arokem** [comment]
Super!

**Pull request merged**
