### PR TITLE
[RF] fix dki mask for nlls

### LINKED ISSUE #2994: DKI masking
https://github.com/dipy/dipy/blob/7e158ffa52b81710f3a1b0d6afa3a364f42a650c/dipy/reconst/dki.py#L1678

I think, as mentioned in #2730, that the masking in the DKI function is not working properly except for the `multi_fit` method, because the mask does not appear to be passed into general fitting functions. Can I confirm that this appears to be the case?

### PR DESCRIPTION
**Pull request by skoudoro**
this PR should fix #2994.

it makes sure that we use the mask for NLLS fitting. This feature has been removed accidentally on previous PR. 

I added a test to make sure we can catch it next time.

### CODE REVIEW

**Comment by skoudoro** [comment]
@samcoveney, can you have a look at this?

Thank you

**Comment by skoudoro** [comment]
Also, @RafaelNH can you have a quick look at this?

Thank you

**Comment by Garyfallidis** [comment]
@samcoveney can you check this PR? Thank you in advance.

**Comment by skoudoro** [comment]
Can you have a look @samcoveney or @RafaelNH or @arokem?

**Comment by samcoveney** [comment]
Hi @skoudoro sorry about my tardy respone, let me look now

**Comment by samcoveney** [comment]
I think this is going to conflict with #3078 because of the additional returns of S0 that I have coded in. It wouldn't be too difficult to rebase this PR off #3078 ? I think using NLLS for DKI is very rare, so this is less of a priority?

**Comment by samcoveney** [comment]
Happy to help here, I appreciate you working off #3078

**Pull request merged**
