### PR TITLE
TRX integration, requires new attributes for SFT

### PR DESCRIPTION
**Pull request by frheault**
This is a small addition for an attribute in the StatefulTractogram that would help the manipulation for the TRX file format.
https://github.com/tee-ar-ex/trx-python/pull/50

### CODE REVIEW

**Comment by arokem** [comment]
Hey @frheault : looks good to me! Admittedly, this is all really straightfoward, but could you add a test that exercises this code?

**Comment by frheault** [comment]
@arokem @skoudoro I added tests. And I realized that there were 3 styles of tests in one file so I uniformized them a bit to make it easier to incorporate my new tests.

Overall, I think no one (except the TRX library) will use this attribute, but I made the test robust enough to realize my previous code was somewhat 'dangerous' (and so I made it a bit better)

**Comment by skoudoro** [comment]
Thank you for the update @frheault.

it seems, it is still failing sometimes:
```python
_______________________ test_init_dtype_dict_attributes _______________________

    def test_init_dtype_dict_attributes():
        sft = load_tractogram(filepath_dix['gs.trk'], filepath_dix['gs.nii'])
        dtype_dict = {'positions': np.float64,
                      'offsets': np.int64,
                      'dpp': {'color_x': np.float32,
                              'color_y': np.float32,
                              'color_z': np.float32},
                      'dps': {'random_coord': np.float32}}
>       assert_(dtype_dict == sft.dtype_dict)
E       AssertionError
```

Can you look why ?

Thank you

**Comment by frheault** [comment]
@skoudoro I have no idea why, it's working on my ubuntu 20.04 and 22.04 with Python 3.7 to 3.10.

Its a simple dictionary comparison, I don't understand 😐

**Comment by Garyfallidis** [comment]
@frheault on the same topic of TRX integration. Do we have any examples showing how to save clustering labels (or similar) using the TRX format?

**Comment by frheault** [comment]
@skoudoro It seems like my change worked for most platforms.
I used np.double, np.single and np.int_ to be platform-specific in the initialisation test (so when we load trk we match the nibabel datatype.

However, I don't know why it failed on Compat / minimal-py37. Is it possible to have some info on the architecture (32 bits vs 64 bits, or anything related to what could impact default datatype for numpy or in memory int32/int64 or float32/float64)
```
dtype_dict = {'positions': np.double,
                  'offsets': np.int_,
                  'dpp': {'color_x': np.single,
                          'color_y': np.single,
                          'color_z': np.single},
                  'dps': {'random_coord': np.single}}
```

**Comment by skoudoro** [comment]
it is still failing, Can you check @frheault if it works on your environment with `numpy-1.17.5` ?   I will check on my side also.

Thank you

**Comment by frheault** [comment]
@skoudoro my issue has been fixed, it was related to nibabel now using an float64 affine.

The test crashing aren't related to my PR.

**Comment by skoudoro** [comment]
Thank you for digging @frheault. I just restarted the failing CIs. After that, it should be go.

**Pull request merged**
