### PR TITLE
base tests

### PR DESCRIPTION
**Pull request by maharshi-gor**

### CODE REVIEW

**Comment by skoudoro** [comment]
Hi @maharshi-gor ? 

What is the status of this PR?  Should I expect to be ready before next Wednesday or I should remove it from the future release ?

Thank you for the feedback

**Comment by maharshi-gor** [comment]
Hi @skoudoro , this PR is deprioritized as we have many bugs to solve. We should not be counting it as the release candidate. It will be picked up as clean-up once all the basic bugs are fixed.

**Comment by skoudoro** [comment]
ok, Thank you for the update.

**Comment by skoudoro** [comment]
> Hi @skoudoro , this PR is deprioritized as we have many bugs to solve.

Due this comment and the current branch conflict, closing this PR for now.

Feel free to reopen it when you have finalized this PR and ready for a merging version. 

Thanks

**Pull request closed without merging**
