### PR TITLE
DOC: Miscellaneous doc formatting fixes (part 3)

### PR DESCRIPTION
**Pull request by jhlegarreta**
- DOC: Add documentation build action status badge to README
- DOC: Enclose absolute value math expression within LaTeX markup
- DOC: Add missing description to parameters across methods
- DOC: Add blank line before list
- DOC: Remove unnecessary indentation in documentation block
- DOC: Remove unnecessary indentations in citation text in examples
- DOC: Indent appropriately documentation block after `note` directive
- DOC: Use accurate citation cross-reference keys

### CODE REVIEW

**Comment by jhlegarreta** [comment]
Re 0a52f6a there is probably dozens of other cases where parameters are not documented, even for the methods where this particular patch set has edited, and which will make the error be pointed a few lines after. But it is a step forward.

**Comment by jhlegarreta** [comment]
1186 warnings left after this PR:
https://github.com/dipy/dipy/actions/runs/10275303515/job/28433690002?pr=3304#step:5:2448

compared to 1284 before this PR:
https://github.com/dipy/dipy/actions/runs/10269802236/job/28416082327#step:5:2546

Compared to the initial 1398:
https://github.com/dipy/dipy/actions/runs/9982200633/job/27587486843#step:5:2618

**Comment by jhlegarreta** [comment]
Build failures are unrelated.

**Review by skoudoro — APPROVED** [review]
LGTM, merging, thanks @jhlegarreta

**Pull request merged**
