### PR TITLE
[ENH] Add inplace kwarg to gibbs_removal

### LINKED ISSUE #2237: gibbs_removal overwrites input data when inputting 3-d or 4-d data.
## Description
`gibbs_removal` overwrite input data when inputting 3-d or 4-d data that happens on this line. https://github.com/dipy/dipy/blob/c1c43b4ea71086682a5b408b539274495a9052cb/dipy/denoise/gibbs.py#L291 I doubt this is intentional, but is an easy fix by simply making a copy of the input data in the beginning or creating an empty array to write into.

## Way to reproduce
[If reporting a bug, please include the following important information:]
- [x] Code example

> import numpy as np
> from dipy.denoise.gibbs import gibbs_removal
> 
> X = np.random.normal(size=(50, 50, 25))
> Y = X.copy()
> _ = gibbs_removal(X)
> np.array_equal(X, Y)
> False

- [ ] Relevant images (if any)
- [x] Operating system and version (run `python -c "import platform; print(platform.platform())"`)
  - Darwin-19.6.0-x86_64-i386-64bit
- [x] Python version (run `python -c "import sys; print("Python", sys.version)"`)
  - Python 3.7.9
- [x] dipy version (run `python -c "import dipy; print(dipy.__version__)"`)
  - Dipy 1.2.0
- [x] dependency version (numpy, scipy, nibabel, h5py, cvxpy, fury)
  - NumPy 1.19.1
  - SciPy 1.5.2
  - Nibabel 3.1.1
  - H5py 2.10.0

### PR DESCRIPTION
**Pull request by j1c**
Added `inplace` kwarg to `gibbs_removal`. Set to `True` by default. The inplace behavior is consistent regardless of the dimensionality of input data. 

Note that I had to modify the original tests by adding `inplace=False` in some cases to keep the original behavior, which assumed 2d inputs always returned a copy.

Closes #2237

### CODE REVIEW

**Comment by skoudoro** [comment]
Thank you for this @j1c!

After a first quick look, the code looks good, and thanks for adding tests! We will look at the code deeper later in the day and come back to you.

**Comment by j1c** [comment]
Actually, upon second thought, I think its better for `inplace` to default to False. I will let you guys make that decision.

**Comment by skoudoro** [comment]
> Actually, upon second thought, I think its better for inplace to default to False. I will let you guys make that decision.

I do not have any strong opinion about `inplace` to `False`. For backward compatibilities and to not surprise the users, I would keep it to `True`.  

What do you think @arokem, @garyfallidis, others ?

**Comment by skoudoro** [comment]
This PR is ready to be merged, I will wait for another opinion to your question @j1c until the end of the week. If no answer, I will merge it as it is.

**Comment by arokem** [comment]
+1 for inplace=True. You could make pretty good arguments for  either of these  and only one is fully back-compatible

**Comment by skoudoro** [comment]
Ok so here we go! Thanks again @j1c!

**Pull request merged**
