### PR TITLE
RF: Update pyproject.toml for numpy 2.0

### PR DESCRIPTION
**Pull request by skoudoro**
> A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

make sure that we always build DIPY with `numpy>=2.0.0rc1`

### CODE REVIEW

**Comment by skoudoro** [comment]
ok, it works as expected, just 1-2 warnings to clean and it will be ready to go. 

here the warnings:
```
testing/__init__.py::dipy.testing.clear_and_catch_warnings
  <doctest dipy.testing.clear_and_catch_warnings[2]>:1: DeprecationWarning: numpy.core is deprecated and has been renamed to numpy._core. The numpy._core namespace contains private NumPy internals and its use is discouraged, as NumPy internals can change without warning in any release. In practice, most real-world usage of numpy.core is to access functionality in the public NumPy API. If that is the case, use the public NumPy API. If not, you are using NumPy internals. If you would still like to access an internal attribute, use numpy._core.fromnumeric.
  ```

I might close #3266 in favor of this PR.

**Comment by skoudoro** [comment]
ok, all good. The first warning fixed also. 

I do not succeed to generate the second warning locally ( this warning is triggered only on macOS). 
if I do not succeed to fix it, I will just ignore this warning on `pyproject.toml`

**Comment by skoudoro** [comment]
This PR is ready to go - @arokem and @jhlegarreta.   It finalizes the compatibility with Numpy 2.0 

I have corrected the 2 warnings above but it seems 2 others warnings are there. I will fix them in new PR.

Feel free to merge.  Thanks!

**Review by arokem — APPROVED** [review]

**Comment by skoudoro** [comment]
Thanks @arokem !

Note: one of the failing matrix is waiting the the new release of `pytables` because current release does not have support of arm64. see https://github.com/PyTables/PyTables/issues/1165

**Comment by jhlegarreta** [comment]
:+1: The cvxpy warning was present in some builds a while ago, but the following PR solved the issue at that time:
https://github.com/dipy/dipy/pull/3183

Looks like we are missing something else.

**Comment by skoudoro** [comment]
I agree

**Pull request merged**
