### PR TITLE
Vara's week 5 blog

### PR DESCRIPTION
**Pull request by lb-97**

### CODE REVIEW

**Comment by shilpiprd** [comment]
Vara, one suggestion I'd like to give is that , before you post a blog anywhere, you should probably post the entire blog on a google doc page because that would highlight all your spelling and grammatical mistakes, and you can make the changes right with just one click.

**Comment by lb-97** [comment]
@s

> Vara, one suggestion I'd like to give is that , before you post a blog anywhere, you should probably post the entire blog on a google doc page because that would highlight all your spelling and grammatical mistakes, and you can make the changes right with just one click.

Yes, that's a great idea. Done! Can you approve my PR? Thanks.

**Review by shilpiprd — APPROVED** [review]

**Review by skoudoro — COMMENTED** [review]
Thank you for the review @shilpiprd.

Can you move the files in static/images @lb-97 ? 

Thanks !

**Comment by skoudoro** [comment]
Also, there is already a PR for the blog 4, Can you remove it from this PR (to avoid overriding good change) ?

**Review by skoudoro — COMMENTED** [review]
Hi @lb-97,

- Can you rebase this PR, there are some conflicts since blog 4 has been merged
- Can you move the files in static/images @lb-97 ?

Apart from that, all good ! Looking forward to your update
-

**Comment by lb-97** [comment]
> Hi @lb-97,
> 
> * Can you rebase this PR, there are some conflicts since blog 4 has been merged
> * Can you move the files in static/images @lb-97 ?
> 
> Apart from that, all good ! Looking forward to your update

Done! Thanks for your comments.

**Review by skoudoro — APPROVED** [review]
Thank you for the update merging

**Pull request merged**
