### PR TITLE
Robust split idea rebase tidy

### PR DESCRIPTION
**Pull request by arokem**
Supersedes #3401 

Also, rebased on master again just now.

### CODE REVIEW

**Comment by skoudoro** [comment]
Thanks!

However, this rebase, is missing, my last commit with build docs fix.

I suppose, you forgot to git pull before creating a new branch.

**Comment by arokem** [comment]
Yeah. Sorry about that. Let me see if I can cherry-pick that in.

**Comment by skoudoro** [comment]
> That took a bit of git-fu 😅

lol, I can imagine 🤣

**Comment by skoudoro** [comment]
All CIs green ! 

<details>
<summary>git log seems to be correct with all credits</summary>
<br>
commit 3a3aebe21ef525d143da399a1ae0636fc4132ddf (HEAD -> pr/arokem/3403, arokem/robust_split_idea_rebase_tidy)
Author: Serge Koudoro 
Date:   Mon Nov 4 22:55:35 2024 -0500

    doc: fix formatting issue

commit 025151014f7805ccdf6ff340c92cb72fe98aeb86
Author: Ariel Rokem
Date:   Mon Nov 4 15:10:14 2024 -0800

    Formatting, remove unused variable.

commit 169878fdaa1959fefbba4ec622eec52d24ebdc26
Author: Ariel Rokem 
Date:   Mon Nov 4 10:43:29 2024 -0800

    Formatting and eliminating unused variables.

commit 522fa587643a4d6ee6e4527182eadfb0f7cb61c4
Author: Sam Coveney 
Date:   Wed Oct 30 12:18:00 2024 +0000

commit 57806ff09e852d2b00ddcd8dc6015f5889c8aba5
Author: Sam Coveney
Date:   Wed Oct 30 09:17:50 2024 +0000

    temp fix for test_nnls_jacobian_func

commit ccec4043931533a95ca3c1c9e75febf21443ea5b
Author: Sam Coveney 
Date:   Tue Oct 29 16:45:29 2024 +0000

    placeholders for weights tests

commit 4f027d6319f31757f9f71c856474052c89b83e82
Author: Sam Coveney 
Date:   Tue Oct 29 16:25:29 2024 +0000

    fixed up the PR based on comments

commit 86aecd0ffb12bac791297413bf90a2a71bc84b28
Author: Sam Coveney 
Date:   Wed Oct 2 10:21:14 2024 +0100

    pep8 for weights_method.py

commit cc657b90a7666fc7129b523c93e3a639d004356f
Author: Sam Coveney 
Date:   Wed Oct 2 10:17:09 2024 +0100

    pep8 for test_dti.py

commit 66155a82fc261ac043c32a5e4c4a88b58b42835a
Author: Sam Coveney 
Date:   Wed Oct 2 10:14:15 2024 +0100

    pep8 for multi_voxel.py

commit 3db924916fb99757d97a5325e93f8379e2e775ff
Author: Sam Coveney 
Date:   Wed Oct 2 10:11:13 2024 +0100

    pep8 for dti.py again 2

commit ec7dc6deaaa43dc2f52f5c05111a87c5a548d9c5
Author: Sam Coveney 
Date:   Wed Oct 2 10:10:17 2024 +0100

    pep8 for dti.py again

commit c472dbef3e17c6d7b8b4cf13040af2557ce9a9cf
Author: Sam Coveney 
Date:   Wed Oct 2 10:08:53 2024 +0100

    pep8 for dti.py

commit 9b9c9be9ac71fdc64f53713039e99ec37c96c156
Author: Sam Coveney 
Date:   Wed Oct 2 09:58:11 2024 +0100

    pep8 hanging indent again

commit 650800850e730bcf8eeb0f5dc2f8a0567d050ced
Author: Sam Coveney 
Date:   Wed Oct 2 09:53:03 2024 +0100

    pep8 hanging indent

commit af32b809c61f16d8a018e35934afc0bc4a028206
Author: Sam Coveney 
Date:   Wed Sep 25 11:45:19 2024 +0100

    tests work

commit d0e13e2bcb217723cd479b1e41b9555b987dbdcf
Author: Sam Coveney 
Date:   Wed Sep 25 10:52:31 2024 +0100

    pep8 fixes

commit c14208f6ddf421cdfca931a0d3f667d08c4d09e3
Author: Sam Coveney 
Date:   Wed Apr 19 11:39:24 2023 +0100

    robust algorithm
    
    syntax fix
    
    syntax fix 2
    
    split weights from outlier definition
    
    fixed after handling terrible rebase
    
    proof of bug in someone elses PR
    
    removed the ipython embed
    
    outlier updates only
    
    force serial to avoid DiPy bug

</details>

So I am going ahead and merge this PR! 

Thank you for the rebase @arokem. Thank you for this work @samcoveney!

ps: I will also create few issues for the latest tasks

**Comment by samcoveney** [comment]
Thanks @arokem and @skoudoro and @jhlegarreta for helping to get this over the line.

**Pull request merged**
