### PR TITLE
DOC: http:// → https://

### PR DESCRIPTION
**Pull request by DimitriPapadopoulos**

### CODE REVIEW

**Review by skoudoro — APPROVED** [review]
LGTM, Thank you @DimitriPapadopoulos for updating many links also ! merging

**Comment by skoudoro** [comment]
oh ok, it is a draft, I can not merge for now. but it looks good for now

**Comment by DimitriPapadopoulos** [comment]
I think this merge request ready for a review. The remaining `http://` links need extra care to be updated or maybe even removed.

About the PEP8 warnings: I have fixed some of them, I think the remaining ones make no sense. Is it possible to bypass them?

**Comment by skoudoro** [comment]
> The remaining http:// links need extra care to be updated or maybe even removed.

I agree, it can be done on new PR. Thanks 

> About the PEP8 warnings: I have fixed some of them, I think the remaining ones make no sense. Is it possible to bypass them?

Yes, it is possible, just  add `# noqa: E501` at the end of the long sentence/url

e.g : `https://www.sphinx-doc.org/en/stable/index.html    # noqa: E501`

Can you add that then, I can go ahead and merge

**Comment by skoudoro** [comment]
Thanks for the update, merging

**Pull request merged**
