### PR TITLE
Make single and multi tensor simulations compatible with btensors

### PR DESCRIPTION
**Pull request by RafaelNH**
In this PR, I am adapting the single and multi tensor simulations to run with the gradiant_table btensor when this is not None. 

This PR will be usefull to carry on with the implemenation of techniques based on advanced diffusion sequences - in particular for code testing.

### CODE REVIEW

**Comment by RafaelNH** [comment]
Hi @fnery and @kerkelae! Can you give a look to this? Only 51 lines of code to review and I think this may be usefull for the testing of multidimensional encoding implementations.

**Comment by RafaelNH** [comment]
Hi @kerkelae - very nice point! I will update the docstring 👍 !!!

**Comment by arokem** [comment]
Looks great! Did you have a chance to update that docstring? I think the CI failures are unrelated.

**Comment by skoudoro** [comment]
I confirm CI's failures are unrelated.

This PR is almost ready to go! Can you just update this docstring please @RafaelNH?

Thank you!

**Comment by RafaelNH** [comment]
Done! Sorry for delay!

**Comment by skoudoro** [comment]
Great! Thank you @RafaelNH.  Can you give a last look @fnery and @kerkelae before we merge this PR?

Thank you!

**Comment by arokem** [comment]
This looks good to me. Any ideas why Travis is still pending? Looks like the last push here was 5 days ago.

**Comment by skoudoro** [comment]
No idea, When you go to the specific build on Travis [here](https://travis-ci.com/github/dipy/dipy/builds/189076331), everything is ok and green, the build passed. 

So I think, it is just a UI bug.

+1 for merging

**Pull request merged**
