### PR TITLE
Adding Week 11 Blog

### PR DESCRIPTION
**Pull request by shilpiprd**

### CODE REVIEW

**Review by skoudoro — CHANGES_REQUESTED** [review]
Before a deeper review, can you 

- check again all the markup:
  * filename, code, function name, etc with backtick
  * remove all the underscore of design matrix
- make shorter sentences to improve readability

Thanks

**Comment by shilpiprd** [comment]
Yeah, sure !

**Comment by shilpiprd** [comment]
So, I've made some modifications. Please let me know if any change needs to be made in any of the blog posts. 
Thanks,

**Comment by skoudoro** [comment]
Thanks @shilpiprd, merging

**Pull request merged**
