### PR TITLE
changed buan_flow.rst to BUAN_flow.rst

### PR DESCRIPTION
**Pull request by BramshQamar**
This change is in support of the submission to the paper.

### CODE REVIEW

**Comment by skoudoro** [comment]
Hi @BramshQamar,

Why do you rename it to uppercase ? @Garyfallidis rename it to lower case in a previous commit. I think lower case for a file name is the best but you both have to agree because this is the back and forward

**Comment by Garyfallidis** [comment]
In the paper we linked the capitalized version of the filename. We can change this when we hear back from the reviewers.

**Comment by Garyfallidis** [comment]
@BramshQamar please add an issue as a reminder.

**Comment by BramshQamar** [comment]
Hi @Garyfallidis and @skoudoro,

Issue created #2153. Will fix the issue once we get the review.

**Pull request merged**
