### PR TITLE
[NF] Add workflow to convert tensors in different formats

### PR DESCRIPTION
**Pull request by skoudoro**
This PR allow the possible to convert tensor files from different software.  it should help user to import their data from other software or visualize data processed by DIPY in other software.

### CODE REVIEW

**Comment by skoudoro** [comment]
Did you have the opportunity to try @tangwei?

**Comment by tangwei** [comment]
> Did you have the opportunity to try @tangwei?

I tried to install from the branch following your video instruction. I came to the point of checkout, but after I clicked the checkout button on the pull request description page:

image


I found myself in "pr/skoudoro/3053" rather than "convert-tensors":

image


I ran `pip install .` but it doesn't seem to be the correct version and doesn't have convert_tensors.

image
image


I then tried `pip install --no-build-isolation -v -e .`, and this time the installation failed. Below is the output. I suspect the checkout took me to a wrong branch?

> Using pip 22.3.1 from /Users/wei/anaconda3/lib/python3.10/site-packages/pip (python 3.10)
Obtaining file:///Users/wei/dipy/dipy
  Running command Checking if build backend supports build_editable
  Checking if build backend supports build_editable ... done
ERROR: Exception:
Traceback (most recent call last):
  File "/Users/wei/anaconda3/lib/python3.10/site-packages/pip/_internal/cli/base_command.py", line 160, in exc_logging_wrapper
    status = run_func(*args)
  File "/Users/wei/anaconda3/lib/python3.10/site-packages/pip/_internal/cli/req_command.py", line 247, in wrapper
    return func(self, options, args)
  File "/Users/wei/anaconda3/lib/python3.10/site-packages/pip/_internal/commands/install.py", line 400, in run
    requirement_set = resolver.resolve(
  File "/Users/wei/anaconda3/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 73, in resolve
    collected = self.factory.collect_root_requirements(root_reqs)
  File "/Users/wei/anaconda3/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 491, in collect_root_requirements
    req = self._make_requirement_from_install_req(
  File "/Users/wei/anaconda3/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 453, in _make_requirement_from_install_req
    cand = self._make_candidate_from_link(
  File "/Users/wei/anaconda3/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 185, in _make_candidate_from_link
    self._editable_candidate_cache[link] = EditableCandidate(
  File "/Users/wei/anaconda3/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 322, in __init__
    super().__init__(
  File "/Users/wei/anaconda3/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 162, in __init__
    self.dist = self._prepare()
  File "/Users/wei/anaconda3/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 231, in _prepare
    dist = self._prepare_distribution()
  File "/Users/wei/anaconda3/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 332, in _prepare_distribution
    return self._factory.preparer.prepare_editable_requirement(self._ireq)
  File "/Users/wei/anaconda3/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 633, in prepare_editable_requirement
    dist = _get_prepared_distribution(
  File "/Users/wei/anaconda3/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 69, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(
  File "/Users/wei/anaconda3/lib/python3.10/site-packages/pip/_internal/distributions/sdist.py", line 61, in prepare_distribution_metadata
    self.req.prepare_metadata()
  File "/Users/wei/anaconda3/lib/python3.10/site-packages/pip/_internal/req/req_install.py", line 527, in prepare_metadata
    and self.supports_pyproject_editable()
  File "/Users/wei/anaconda3/lib/python3.10/site-packages/pip/_internal/req/req_install.py", line 241, in supports_pyproject_editable
    return "build_editable" in self.pep517_backend._supported_features()
  File "/Users/wei/anaconda3/lib/python3.10/site-packages/pip/_vendor/pep517/wrappers.py", line 160, in _supported_features
    return self._call_hook('_supported_features', {})
  File "/Users/wei/anaconda3/lib/python3.10/site-packages/pip/_vendor/pep517/wrappers.py", line 319, in _call_hook
    raise BackendUnavailable(data.get('traceback', ''))
pip._vendor.pep517.wrappers.BackendUnavailable: Traceback (most recent call last):
  File "/Users/wei/anaconda3/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 77, in _build_backend
    obj = import_module(mod_path)
  File "/Users/wei/anaconda3/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'mesonpy'

**Comment by skoudoro** [comment]
> I found myself in "pr/skoudoro/3053" rather than "convert-tensors":

The branch is correct

> I then tried pip install --no-build-isolation -v -e .

this is correct. Before that, you need to do `pip install -r requirements/build.txt`.   you are just missing some package

Let me know if it goes ok @tangwei . Thanks !

**Comment by tangwei** [comment]
Ah okay, now it installed correctly and I saw dipy_convert_tensors. I don't have tensor files from other software for testing though. @skoudoro do you know if there are test data somewhere I could use directly?

**Comment by skoudoro** [comment]
>  @skoudoro do you know if there are test data somewhere I could use directly?

No, sorry...

**Comment by skoudoro** [comment]
Do you have an update on this @tangwei ?

**Comment by tangwei** [comment]
The installation worked and I can pull up -help no problem. But I don't have data to test it. I basically don't have tensor files from other software.

**Comment by skoudoro** [comment]
in this case, the easy way is:

- get dipy tensor
- convert to fsl tensor
- open with fsleyes the new tensor (it should look good)
- open with fsleyes dipy tensor
- open with dipy_horizon both tensor also (it should be different)

**Comment by tangwei** [comment]
Got ya. Will do!

**Comment by tangwei** [comment]
> in this case, the easy way is:
> 
> * get dipy tensor
> * convert to fsl tensor
> * open with fsleyes the new tensor (it should look good)
> * open with fsleyes dipy tensor
> * open with dipy_horizon both tensor also (it should be different)

@skoudoro I followed the DIPY tutorial to create tensor variables, but what file format should I save them as? Can you give me an example for the dipy tensor output?

**Comment by skoudoro** [comment]
Hi @tangwei,

You can look at dipy DTI tutorial: https://docs.dipy.org/stable/examples_built/reconstruction/reconst_dti.html#sphx-glr-examples-built-reconstruction-reconst-dti-py

We save tensor as Nifti.

Another example: https://github.com/dipy/miccai23/blob/main/quantconn/process.py#L103-L112

I hope it helps.

**Pull request merged**
