### PR TITLE
DOC: Miscellaneous documentation improvements

### PR DESCRIPTION
**Pull request by jhlegarreta**
- DOC: Do not use raw strings where not necessary
- DOC: Increase consistency in optional argument syntax
- DOC: Remove default values from docstrings

### CODE REVIEW

**Comment by jhlegarreta** [comment]
Branched on top of #3316, so depends on it.

**Comment by skoudoro** [comment]
Can you rebase this PR @jhlegarreta, thank you

**Comment by skoudoro** [comment]
Hi @jhlegarreta,

Do you plan to continue to work on this draft or it should be closed? 

maybe it just need a rebase. What is the plan ?

**Comment by jhlegarreta** [comment]
> Do you plan to continue to work on this draft or it should be closed?

> maybe it just need a rebase. What is the plan ?

It requires work: it has a number of conflicts. I will work on this as time permits. Trying to bring down to zero the doc build errors/warnings has been labor-intensive over the past weeks.

**Comment by jhlegarreta** [comment]
Rebased on `master`, fixed conflicts.

**Review by skoudoro — APPROVED** [review]
All good, Thank you for this @jhlegarreta, 

merging

**Pull request merged**
