### PR TITLE
[UPCOMING] Release preparation for 1.9.0

### PR DESCRIPTION
**Pull request by skoudoro**
Preparation for 1.9.0 release, targeting **March 5-6, 2024**.

# Desired PR / issues (need review / feedback / update)

## PR

- [x]  #3081(Submitter: @praitayini)
- [x] #3078 (Submitter: @samcoveney)
- [x] #3073 (Submitter: @skoudoro)
- [x] #3053 (Submitter: @skoudoro)
- [x] #3048 (Submitter: @skoudoro)
- [x] #3033 (Submitter: @skoudoro)
- [x] #2973 (Submitter: @maharshi-gor)
- [ ] #2826 (Submitter: @CHrlS98)

## Issues / Feature without PR yet

- [x] #3079
- [ ] #3030
- [ ] #3029
- [x] #2994

Most of them can be done on time, I think :smile:

Please comment to flag any other issues or PR that should be addressed for this release

# Release checklist
- [x] add release_notes 1.9.0
- [ ] Update changelog and api_changes
- [x] Update .mailmap
- [ ] Set release number in info.py
- [x] Check the copyright years in doc/conf.py and LICENSE
- [x] Check documentation
- [x] Check Tutorial
- [x] Check unit test and USE-PRE
- [x] Update index.rst
- [x] Update Highligth.rst, old_news.rst, stateofheart.rst
- [ ] Update developers.rst list
- [ ] Update website
- [x] Update deprecation cycle remove long deprecation

### CODE REVIEW

**Comment by skoudoro** [comment]
Ok, This PR is ready, 

Can you have a look @arokem or @Garyfallidis?  Everyone else is also welcome?  Then, I can start the release process.

Thank you

**Comment by arokem** [comment]
I'd say that out of the issues without a PR, #3079 seems the most important to address before a release. I think we can punt the other ones to the next cycle. Or do you think we should punt that one too? 

Also, I'd love to understand #3108 better before we make a release, because I am not at all sure that's not a regression. @maharshi-gor or @Garyfallidis : could you tell me a bit more about that PR?

**Comment by skoudoro** [comment]
Thank you for the feedback @arokem,

- #3079 has been fixed by #3080. I just forgot to close this issue
- Concerning #3108, I will let them answer

**Comment by maharshi-gor** [comment]
Hello @arokem, this is simply enabling the .trx file format in the horizon CLI. CLI was accepting all the types of tractorgrams except the '.trx' extension. Although the method load_tractogram already had the handling of '.trx' files. I just verified if it is a '.trx' file and passed it to the same method to process.

It is tested with a few examples. Let me know if you would like to know more.

Thank you for the feedback.

**Comment by maharshi-gor** [comment]
@arokem the interactions were not working due to the initial setting. The clusters tab had some bugs and we thought it had something to do with how the reference is passed. It was merged because it worked. It was last minute change for the CLI to support .trx.

Before #3108, there was #3107, where we added the .trx support. The interactions on the horizon tab didn't work. But by introducing #3108 change the interaction started working for .trx files.

**Comment by arokem** [comment]
Got it! Just to confirm: since this change is local to viz, this presumably wouldn't affect other parts of the code?

**Pull request merged**
