### PR TITLE
NF: Fibonacci Hemisphere

### PR DESCRIPTION
**Pull request by deka27**
# Added Fibonacci Hemisphere

## Description
- This pull request introduces a new feature: the Fibonacci Hemisphere function, added to the core functionality of the project.

## Changes Made
* Added Fibonacci Hemisphere function to core.
* Added Test for Fibonacci Hemisphere.

## Screenshots

image

## Checklist
- [x] I have reviewed my own code changes.
- [x] I have tested my changes locally.
- [x] My code follows the project's coding standards.

### CODE REVIEW

**Comment by pjsjongsung** [comment]
Hello Thanks for your PR. Since there seems to be no related issues, is there a reason for this commit?

**Comment by deka27** [comment]
> Hello Thanks for your PR. Since there seems to be no related issues, is there a reason for this commit?

Hello @pjsjongsung, thank you for your feedback. The reason behind this commit is the introduction of a new feature, the Fibonacci Hemisphere function, which I believe enhances the core functionality of the project. While there were no specific related issues, I identified this as an opportunity to enrich the project's capabilities. Please let me know if you have any further questions or suggestions regarding this addition. Thank you.

**Comment by arokem** [comment]
Looks interesting. Do you have any references about this method that we could read to understand it and/or add to the documentation? From a quick search I found this:https://extremelearning.com.au/how-to-evenly-distribute-points-on-a-sphere-more-effectively-than-the-canonical-fibonacci-lattice/, but I was wondering whether there is any application in diffusion MRI that you can point to, and that we can refer to in the documentation. 

Another comment is that I think that the documentation needs to mention that if n<30 the charge dispersion algorithm takes over.

**Comment by jhlegarreta** [comment]
This is almost exactly the same feature as the one added in PR #3013, with the sole exception of this one being applied to the hemisphere. The code is almost exactly the same, so if the hemisphere case is still useful, there is probably a way to refactor the existing function to consider a hemisphere or a hemisphere.

**Comment by skoudoro** [comment]
+1 for the refactoring, like @jhlegarreta said above, this is almost the same code... 
Adding an optional argument should do the job.

**Comment by skoudoro** [comment]
also, can you squash your commit @deka27? thank you

**Comment by arokem** [comment]
Oh yeah - this seemed familiar. +1 to combining these two into one function.

**Comment by deka27** [comment]
Understood, I will the refactor existing function. Thank you for the feedback.

**Comment by deka27** [comment]
I have refactored the code as discussed earlier.

**Review by skoudoro — APPROVED** [review]
is there any additional comment @arokem or @pjsjongsung?

I think this PR is ready to be merged. 

I will go ahead tomorrow if no news. Thank you for your feedback!

**Comment by skoudoro** [comment]
Thank you for this work @deka27

**Pull request merged**
