### PR TITLE
RF: Swallow a couple of warnings that are safe to ignore.

### PR DESCRIPTION
**Pull request by arokem**
Also, fixes a typo in the warning in core.gradients.

### CODE REVIEW

**Comment by arokem** [comment]
Do you understand what's up here? https://dev.azure.com/dipy/dipy/_build/results?buildId=6&view=logs&j=0d467bef-f31d-5157-7a21-e4463e6da84d&t=298f180a-b05a-55c6-a730-eb5ec5da2277&l=130. Looks unrelated to this PR?

**Comment by skoudoro** [comment]
yes, unrelated to this PR. Look like `cvxpy` is not compatible with python3.8 yet (only on windows).  The same problem with python3.5 but I am less worried because many packages will stop to support python3.5 in March.

Temporary commented on #2038 so if you merge this PR and rebase this one, it should be ok.

**Comment by arokem** [comment]
OK, with #2038 merged, this is  now rebased

**Comment by skoudoro** [comment]
Thanks @arokem, merging

**Pull request merged**
