### PR TITLE
Add support for sequential processing in Gibbs unringing #2757

### PR DESCRIPTION
**Pull request by tanishka321**
##Details:
If Python is not capable of handling multiprocessing within multiprocessing and may crash. Then this format will ensure that if num_processes is set to 1, the function _gibbs_removal_2d will be called sequentially for each slice, avoiding multiprocessing within multiprocessing.

Closes: #2757

### CODE REVIEW

**Comment by skoudoro** [comment]
Hi @tanishka321,

Thank you for working on this. 


As you can see above:
- Can you address the pep8 issues ? Thank you 
- All the tests are failing after your change. Can you have a closer look and check what is going on? You can run all this specific tests locally by doing `pytest -svv dipy/denoise`

Thank you in advance !

```
=========================== short test summary info ============================
FAILED denoise/tests/test_gibbs.py::test_parallel - ValueError: operands could not be broadcast together with shapes (2,96) (96,96)
FAILED denoise/tests/test_gibbs.py::test_inplace - ValueError: operands could not be broadcast together with shapes (2,96) (96,96)
FAILED denoise/tests/test_gibbs.py::test_gibbs_3d - ValueError: operands could not be broadcast together with shapes (2,96) (96,96)
FAILED denoise/tests/test_gibbs.py::test_gibbs_4d - ValueError: operands could not be broadcast together with shapes (4,96) (96,96)
FAILED denoise/tests/test_gibbs.py::test_swapped_gibbs_3d - ValueError: operands could not be broadcast together with shapes (2,96) (96,96)
FAILED denoise/tests/test_gibbs.py::test_swapped_gibbs_4d - ValueError: operands could not be broadcast together with shapes (4,96) (96,96)
FAILED workflows/tests/test_denoise.py::test_gibbs_flow - ValueError: operands could not be broadcast together with shapes (4,96) (96,96)
===== 7 failed, 1010 passed, 64 skipped, 3 warnings in 1752.82s (0:29:12) ======
```

**Comment by skoudoro** [comment]
> If Python is not capable of handling multiprocessing within multiprocessing and may crash.

I am curious. Why python would be able to handle multiprocessing? this is a standard package. I would love to ear more details about that. Can you explain your case ?

**Comment by skoudoro** [comment]
Hi @tanishka321, 

Do you have an update on this?

**Comment by tashrifbillah** [comment]
Multiprocessing within multiprocessing raises the following error:

> daemonic processes are not allowed to have children

**Comment by tashrifbillah** [comment]
This PR should be revived.

**Pull request closed without merging**
