### PR TITLE
make it compatible when number of volume is 2

### PR DESCRIPTION
**Pull request by giulia-berto**
bvecs should be transpose also when number of volume is 2 (bvecs.shape[1] =2)

### CODE REVIEW

**Comment by giulia-berto** [comment]
sure, here are the two files I am having problems with (I had to change the file extension to .txt to be able to upload them)
[bval.txt](https://github.com/dipy/dipy/files/7384669/bval.txt)
[bvec.txt](https://github.com/dipy/dipy/files/7384670/bvec.txt)

**Comment by arokem** [comment]
https://github.com/giulia-berto/dipy/pull/1

**Comment by giulia-berto** [comment]
I made an extra change, what do you think? I should now delete the original change in dipy/io/gradients.py, right?

**Comment by soichih** [comment]
We had cases where people try to process b0-dwi data with only 1 or 2 volumes.

**Pull request merged**
