### PR TITLE
[Fix] Horizon: Binary image loading

### PR DESCRIPTION
**Pull request by guaje**
This PR will allow loading binary images as images instead of contours in Horizon.

### CODE REVIEW

**Comment by skoudoro** [comment]
Please, Can you add some tests @guaje?  

Thank you

**Comment by guaje** [comment]
> @guaje there were 4 bug fixes needed. Are they going to be fixed in this PR because the changes are small? Or multiple PRs are expected? In summary the bugs were: a) Sync slices for multiple images, b) binary images, c) sync peaks and) fix import [horizon.app](http://horizon.app/) should be from dipy.viz import horizon

No, this PR will only address the binary image issue.

**Comment by guaje** [comment]
> Hey @guaje, what is the update concerning this PR?

Once the CIs are done, it should be ready. PTAL.

**Review by skoudoro — APPROVED** [review]
Thank you for the update @guaje. 

I just tried it and all seems good. 

Merging

**Pull request merged**
