### PR TITLE
Add weekly build to azure + update linux matrix

### PR DESCRIPTION
**Pull request by skoudoro**
A quick PR to:

- Update Linux matrices for azure
- Add a weekly build
- remove Travis.yml

### CODE REVIEW

**Comment by skoudoro** [comment]
This PR is ready to go!

it would be great if someone could have a look!

**Comment by skoudoro** [comment]
@Garyfallidis @arokem?

**Comment by skoudoro** [comment]
This PR fixes all failing Matrices on Azure, it will be good if it can go in!

**Comment by arokem** [comment]
Super. Thank you!

**Comment by skoudoro** [comment]
Great, thank you @arokem!

**Pull request merged**
