### PR TITLE
WIP - NF - Tracking with Initial Directions and other tracking parameters

### PR DESCRIPTION
**Pull request by gabknight**
WIP - it needs a first review by @StongeEtienne and @jchoude. Does this will do for SET?

The aim of this PR is to add three new optional parameters to `LocalTracking`:
- `initial_directions` :  specify the initial direction for tractography to follow at the initial seed position. If `initial_directions` is `None` (default), `LocalTracking` calls `DirectionGetter.initial_direction(seed_position)` to get the initial directions (current behavior). This functions return the list of peak at the seed position. In a similar fashion, `initial_directions` contains a list of directions for every seed positions.
  - The tracking works with directions that correspond to vertices on the sphere. Thus, I had to select the vertice the closest to the input direction instead of the actual input direction. i.e. the closest sphere vertice is used as initial direction instead of the given initial directions.
- `unidirectional`: perform the tractography in a single direction from the seeding position, instead of both (default). This is especially useful in conjunction with `initial_direction`, where, for instance, those initial directions could be pointing inward from the cortical surface or outward from subcortical regions.
- `randomized_forward_direction`: Useful in conjunction with `unidirectional`, this parameter allows the tracking to start randomly either in the initial direction or in its opposite direction. If `undirectional is False`, this parameter will only reverse the points order of some streamlines.

### CODE REVIEW

**Comment by gabknight** [comment]
@StongeEtienne, do you think those tracking parameters will do for your future mesh seeding integration?

**Comment by guaje** [comment]
@gabknight I was checking your code and I realized you are importing HemiSphere but you are not using it. Can you please check that?

**Comment by skoudoro** [comment]
What is the status of this PR @gabknight @StongeEtienne?

**Comment by gabknight** [comment]
This needs a bit of work and not required for the next release. let keep this for Dipy 1.1

**Comment by skoudoro** [comment]
Ok Sounds like plan. Thank you for the feedback.

**Comment by gabknight** [comment]
Closed in favor of PRs #2821 and #2825.

**Pull request closed without merging**
